// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	bank "github.com/payroc/payroc-sdk-go/paymentfeatures/bank"
	cards "github.com/payroc/payroc-sdk-go/paymentfeatures/cards"
)

type Client struct {
	Cards *cards.Client
	Bank  *bank.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Cards:   cards.NewClient(options),
		Bank:    bank.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
