// Code generated by Fern. DO NOT EDIT.

package boarding

import (
	json "encoding/json"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	big "math/big"
)

var (
	deleteContactsRequestFieldContactId = big.NewInt(1 << 0)
)

type DeleteContactsRequest struct {
	// Unique identifier for the contact.
	ContactId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteContactsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetContactId sets the ContactId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteContactsRequest) SetContactId(contactId int) {
	d.ContactId = contactId
	d.require(deleteContactsRequestFieldContactId)
}

var (
	retrieveContactsRequestFieldContactId = big.NewInt(1 << 0)
)

type RetrieveContactsRequest struct {
	// Unique identifier for the contact.
	ContactId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveContactsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetContactId sets the ContactId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveContactsRequest) SetContactId(contactId int) {
	r.ContactId = contactId
	r.require(retrieveContactsRequestFieldContactId)
}

var (
	updateContactsRequestFieldContactId = big.NewInt(1 << 0)
)

type UpdateContactsRequest struct {
	// Unique identifier for the contact.
	ContactId int                `json:"-" url:"-"`
	Body      *papisdkgo.Contact `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateContactsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetContactId sets the ContactId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateContactsRequest) SetContactId(contactId int) {
	u.ContactId = contactId
	u.require(updateContactsRequestFieldContactId)
}

func (u *UpdateContactsRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.Contact)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdateContactsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}
