// Code generated by Fern. DO NOT EDIT.

package boarding

import (
	json "encoding/json"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	big "math/big"
)

var (
	deleteOwnersRequestFieldOwnerId = big.NewInt(1 << 0)
)

type DeleteOwnersRequest struct {
	// Unique identifier that we assigned to the owner.
	OwnerId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteOwnersRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetOwnerId sets the OwnerId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteOwnersRequest) SetOwnerId(ownerId int) {
	d.OwnerId = ownerId
	d.require(deleteOwnersRequestFieldOwnerId)
}

var (
	retrieveOwnersRequestFieldOwnerId = big.NewInt(1 << 0)
)

type RetrieveOwnersRequest struct {
	// Unique identifier that we assigned to the owner.
	OwnerId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveOwnersRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetOwnerId sets the OwnerId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveOwnersRequest) SetOwnerId(ownerId int) {
	r.OwnerId = ownerId
	r.require(retrieveOwnersRequestFieldOwnerId)
}

var (
	updateOwnersRequestFieldOwnerId = big.NewInt(1 << 0)
)

type UpdateOwnersRequest struct {
	// Unique identifier that we assigned to the owner.
	OwnerId int              `json:"-" url:"-"`
	Body    *papisdkgo.Owner `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateOwnersRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetOwnerId sets the OwnerId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOwnersRequest) SetOwnerId(ownerId int) {
	u.OwnerId = ownerId
	u.require(updateOwnersRequestFieldOwnerId)
}

func (u *UpdateOwnersRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.Owner)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdateOwnersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}
