// Code generated by Fern. DO NOT EDIT.

package boarding

import (
	json "encoding/json"
	fmt "fmt"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	internal "github.com/payroc/payroc-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	createReminderProcessingAccountsRequestFieldIdempotencyKey      = big.NewInt(1 << 0)
	createReminderProcessingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 1)
)

type CreateReminderProcessingAccountsRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string                                       `json:"-" url:"-"`
	Body                *CreateReminderProcessingAccountsRequestBody `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateReminderProcessingAccountsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateReminderProcessingAccountsRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createReminderProcessingAccountsRequestFieldIdempotencyKey)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateReminderProcessingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	c.ProcessingAccountId = processingAccountId
	c.require(createReminderProcessingAccountsRequestFieldProcessingAccountId)
}

func (c *CreateReminderProcessingAccountsRequest) UnmarshalJSON(data []byte) error {
	body := new(CreateReminderProcessingAccountsRequestBody)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateReminderProcessingAccountsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	createTerminalOrderFieldIdempotencyKey      = big.NewInt(1 << 0)
	createTerminalOrderFieldProcessingAccountId = big.NewInt(1 << 1)
	createTerminalOrderFieldTrainingProvider    = big.NewInt(1 << 2)
	createTerminalOrderFieldShipping            = big.NewInt(1 << 3)
	createTerminalOrderFieldOrderItems          = big.NewInt(1 << 4)
)

type CreateTerminalOrder struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string                      `json:"-" url:"-"`
	TrainingProvider    *papisdkgo.TrainingProvider `json:"trainingProvider,omitempty" url:"-"`
	// Object that contains the shipping details for the terminal order. If you don't provide a shipping address, we use the Doing Business As (DBA) address of the processing account.
	Shipping *CreateTerminalOrderShipping `json:"shipping,omitempty" url:"-"`
	// Array of order items. Provide a minimum of 1 order item and a maximum of 10 order items.
	OrderItems []*papisdkgo.OrderItem `json:"orderItems" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateTerminalOrder) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrder) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createTerminalOrderFieldIdempotencyKey)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrder) SetProcessingAccountId(processingAccountId string) {
	c.ProcessingAccountId = processingAccountId
	c.require(createTerminalOrderFieldProcessingAccountId)
}

// SetTrainingProvider sets the TrainingProvider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrder) SetTrainingProvider(trainingProvider *papisdkgo.TrainingProvider) {
	c.TrainingProvider = trainingProvider
	c.require(createTerminalOrderFieldTrainingProvider)
}

// SetShipping sets the Shipping field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrder) SetShipping(shipping *CreateTerminalOrderShipping) {
	c.Shipping = shipping
	c.require(createTerminalOrderFieldShipping)
}

// SetOrderItems sets the OrderItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrder) SetOrderItems(orderItems []*papisdkgo.OrderItem) {
	c.OrderItems = orderItems
	c.require(createTerminalOrderFieldOrderItems)
}

func (c *CreateTerminalOrder) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTerminalOrder
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateTerminalOrder(body)
	return nil
}

func (c *CreateTerminalOrder) MarshalJSON() ([]byte, error) {
	type embed CreateTerminalOrder
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getProcessingAccountPricingAgreementProcessingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 0)
)

type GetProcessingAccountPricingAgreementProcessingAccountsRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetProcessingAccountPricingAgreementProcessingAccountsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetProcessingAccountPricingAgreementProcessingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	g.ProcessingAccountId = processingAccountId
	g.require(getProcessingAccountPricingAgreementProcessingAccountsRequestFieldProcessingAccountId)
}

var (
	listContactsProcessingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 0)
	listContactsProcessingAccountsRequestFieldBefore              = big.NewInt(1 << 1)
	listContactsProcessingAccountsRequestFieldAfter               = big.NewInt(1 << 2)
	listContactsProcessingAccountsRequestFieldLimit               = big.NewInt(1 << 3)
)

type ListContactsProcessingAccountsRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string `json:"-" url:"-"`
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListContactsProcessingAccountsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsProcessingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	l.ProcessingAccountId = processingAccountId
	l.require(listContactsProcessingAccountsRequestFieldProcessingAccountId)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsProcessingAccountsRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listContactsProcessingAccountsRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsProcessingAccountsRequest) SetAfter(after *string) {
	l.After = after
	l.require(listContactsProcessingAccountsRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContactsProcessingAccountsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listContactsProcessingAccountsRequestFieldLimit)
}

var (
	listProcessingAccountOwnersRequestFieldProcessingAccountId = big.NewInt(1 << 0)
	listProcessingAccountOwnersRequestFieldBefore              = big.NewInt(1 << 1)
	listProcessingAccountOwnersRequestFieldAfter               = big.NewInt(1 << 2)
	listProcessingAccountOwnersRequestFieldLimit               = big.NewInt(1 << 3)
)

type ListProcessingAccountOwnersRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string `json:"-" url:"-"`
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListProcessingAccountOwnersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingAccountOwnersRequest) SetProcessingAccountId(processingAccountId string) {
	l.ProcessingAccountId = processingAccountId
	l.require(listProcessingAccountOwnersRequestFieldProcessingAccountId)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingAccountOwnersRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listProcessingAccountOwnersRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingAccountOwnersRequest) SetAfter(after *string) {
	l.After = after
	l.require(listProcessingAccountOwnersRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingAccountOwnersRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listProcessingAccountOwnersRequestFieldLimit)
}

var (
	listProcessingAccountFundingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 0)
)

type ListProcessingAccountFundingAccountsRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListProcessingAccountFundingAccountsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingAccountFundingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	l.ProcessingAccountId = processingAccountId
	l.require(listProcessingAccountFundingAccountsRequestFieldProcessingAccountId)
}

var (
	listProcessingTerminalsProcessingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 0)
	listProcessingTerminalsProcessingAccountsRequestFieldBefore              = big.NewInt(1 << 1)
	listProcessingTerminalsProcessingAccountsRequestFieldAfter               = big.NewInt(1 << 2)
	listProcessingTerminalsProcessingAccountsRequestFieldLimit               = big.NewInt(1 << 3)
)

type ListProcessingTerminalsProcessingAccountsRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string `json:"-" url:"-"`
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListProcessingTerminalsProcessingAccountsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingTerminalsProcessingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	l.ProcessingAccountId = processingAccountId
	l.require(listProcessingTerminalsProcessingAccountsRequestFieldProcessingAccountId)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingTerminalsProcessingAccountsRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listProcessingTerminalsProcessingAccountsRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingTerminalsProcessingAccountsRequest) SetAfter(after *string) {
	l.After = after
	l.require(listProcessingTerminalsProcessingAccountsRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListProcessingTerminalsProcessingAccountsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listProcessingTerminalsProcessingAccountsRequestFieldLimit)
}

var (
	listTerminalOrdersProcessingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 0)
	listTerminalOrdersProcessingAccountsRequestFieldStatus              = big.NewInt(1 << 1)
	listTerminalOrdersProcessingAccountsRequestFieldFromDateTime        = big.NewInt(1 << 2)
	listTerminalOrdersProcessingAccountsRequestFieldToDateTime          = big.NewInt(1 << 3)
)

type ListTerminalOrdersProcessingAccountsRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string                                             `json:"-" url:"-"`
	Status              *ListTerminalOrdersProcessingAccountsRequestStatus `json:"-" url:"status,omitempty"`
	FromDateTime        *time.Time                                         `json:"-" url:"fromDateTime,omitempty"`
	ToDateTime          *time.Time                                         `json:"-" url:"toDateTime,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListTerminalOrdersProcessingAccountsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTerminalOrdersProcessingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	l.ProcessingAccountId = processingAccountId
	l.require(listTerminalOrdersProcessingAccountsRequestFieldProcessingAccountId)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTerminalOrdersProcessingAccountsRequest) SetStatus(status *ListTerminalOrdersProcessingAccountsRequestStatus) {
	l.Status = status
	l.require(listTerminalOrdersProcessingAccountsRequestFieldStatus)
}

// SetFromDateTime sets the FromDateTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTerminalOrdersProcessingAccountsRequest) SetFromDateTime(fromDateTime *time.Time) {
	l.FromDateTime = fromDateTime
	l.require(listTerminalOrdersProcessingAccountsRequestFieldFromDateTime)
}

// SetToDateTime sets the ToDateTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTerminalOrdersProcessingAccountsRequest) SetToDateTime(toDateTime *time.Time) {
	l.ToDateTime = toDateTime
	l.require(listTerminalOrdersProcessingAccountsRequestFieldToDateTime)
}

var (
	retrieveProcessingAccountsRequestFieldProcessingAccountId = big.NewInt(1 << 0)
)

type RetrieveProcessingAccountsRequest struct {
	// Unique identifier that we assigned to the processing account.
	ProcessingAccountId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveProcessingAccountsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetProcessingAccountId sets the ProcessingAccountId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveProcessingAccountsRequest) SetProcessingAccountId(processingAccountId string) {
	r.ProcessingAccountId = processingAccountId
	r.require(retrieveProcessingAccountsRequestFieldProcessingAccountId)
}

type CreateReminderProcessingAccountsRequestBody struct {
	Type             string
	PricingAgreement *papisdkgo.PricingAgreementReminder
}

func (c *CreateReminderProcessingAccountsRequestBody) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreateReminderProcessingAccountsRequestBody) GetPricingAgreement() *papisdkgo.PricingAgreementReminder {
	if c == nil {
		return nil
	}
	return c.PricingAgreement
}

func (c *CreateReminderProcessingAccountsRequestBody) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	c.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", c)
	}
	switch unmarshaler.Type {
	case "pricingAgreement":
		value := new(papisdkgo.PricingAgreementReminder)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.PricingAgreement = value
	}
	return nil
}

func (c CreateReminderProcessingAccountsRequestBody) MarshalJSON() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	if c.PricingAgreement != nil {
		return internal.MarshalJSONWithExtraProperty(c.PricingAgreement, "type", "pricingAgreement")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", c)
}

type CreateReminderProcessingAccountsRequestBodyVisitor interface {
	VisitPricingAgreement(*papisdkgo.PricingAgreementReminder) error
}

func (c *CreateReminderProcessingAccountsRequestBody) Accept(visitor CreateReminderProcessingAccountsRequestBodyVisitor) error {
	if c.PricingAgreement != nil {
		return visitor.VisitPricingAgreement(c.PricingAgreement)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", c)
}

func (c *CreateReminderProcessingAccountsRequestBody) validate() error {
	if c == nil {
		return fmt.Errorf("type %T is nil", c)
	}
	var fields []string
	if c.PricingAgreement != nil {
		fields = append(fields, "pricingAgreement")
	}
	if len(fields) == 0 {
		if c.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", c, c.Type)
		}
		return fmt.Errorf("type %T is empty", c)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", c, fields)
	}
	if c.Type != "" {
		field := fields[0]
		if c.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				c,
				c.Type,
				c,
			)
		}
	}
	return nil
}

type CreateReminderProcessingAccountsResponse struct {
	Type             string
	PricingAgreement *papisdkgo.PricingAgreementReminder
}

func (c *CreateReminderProcessingAccountsResponse) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreateReminderProcessingAccountsResponse) GetPricingAgreement() *papisdkgo.PricingAgreementReminder {
	if c == nil {
		return nil
	}
	return c.PricingAgreement
}

func (c *CreateReminderProcessingAccountsResponse) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	c.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", c)
	}
	switch unmarshaler.Type {
	case "pricingAgreement":
		value := new(papisdkgo.PricingAgreementReminder)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.PricingAgreement = value
	}
	return nil
}

func (c CreateReminderProcessingAccountsResponse) MarshalJSON() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	if c.PricingAgreement != nil {
		return internal.MarshalJSONWithExtraProperty(c.PricingAgreement, "type", "pricingAgreement")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", c)
}

type CreateReminderProcessingAccountsResponseVisitor interface {
	VisitPricingAgreement(*papisdkgo.PricingAgreementReminder) error
}

func (c *CreateReminderProcessingAccountsResponse) Accept(visitor CreateReminderProcessingAccountsResponseVisitor) error {
	if c.PricingAgreement != nil {
		return visitor.VisitPricingAgreement(c.PricingAgreement)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", c)
}

func (c *CreateReminderProcessingAccountsResponse) validate() error {
	if c == nil {
		return fmt.Errorf("type %T is nil", c)
	}
	var fields []string
	if c.PricingAgreement != nil {
		fields = append(fields, "pricingAgreement")
	}
	if len(fields) == 0 {
		if c.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", c, c.Type)
		}
		return fmt.Errorf("type %T is empty", c)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", c, fields)
	}
	if c.Type != "" {
		field := fields[0]
		if c.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				c,
				c.Type,
				c,
			)
		}
	}
	return nil
}

// Object that contains the shipping details for the terminal order. If you don't provide a shipping address, we use the Doing Business As (DBA) address of the processing account.
var (
	createTerminalOrderShippingFieldPreferences = big.NewInt(1 << 0)
	createTerminalOrderShippingFieldAddress     = big.NewInt(1 << 1)
)

type CreateTerminalOrderShipping struct {
	// Object that contains the shipping preferences for the terminal order.
	Preferences *CreateTerminalOrderShippingPreferences `json:"preferences,omitempty" url:"preferences,omitempty"`
	// Object that contains the shipping address for the terminal order.
	Address *CreateTerminalOrderShippingAddress `json:"address,omitempty" url:"address,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateTerminalOrderShipping) GetPreferences() *CreateTerminalOrderShippingPreferences {
	if c == nil {
		return nil
	}
	return c.Preferences
}

func (c *CreateTerminalOrderShipping) GetAddress() *CreateTerminalOrderShippingAddress {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CreateTerminalOrderShipping) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateTerminalOrderShipping) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPreferences sets the Preferences field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShipping) SetPreferences(preferences *CreateTerminalOrderShippingPreferences) {
	c.Preferences = preferences
	c.require(createTerminalOrderShippingFieldPreferences)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShipping) SetAddress(address *CreateTerminalOrderShippingAddress) {
	c.Address = address
	c.require(createTerminalOrderShippingFieldAddress)
}

func (c *CreateTerminalOrderShipping) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTerminalOrderShipping
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTerminalOrderShipping(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTerminalOrderShipping) MarshalJSON() ([]byte, error) {
	type embed CreateTerminalOrderShipping
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateTerminalOrderShipping) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Object that contains the shipping address for the terminal order.
var (
	createTerminalOrderShippingAddressFieldRecipientName = big.NewInt(1 << 0)
	createTerminalOrderShippingAddressFieldBusinessName  = big.NewInt(1 << 1)
	createTerminalOrderShippingAddressFieldAddressLine1  = big.NewInt(1 << 2)
	createTerminalOrderShippingAddressFieldAddressLine2  = big.NewInt(1 << 3)
	createTerminalOrderShippingAddressFieldCity          = big.NewInt(1 << 4)
	createTerminalOrderShippingAddressFieldState         = big.NewInt(1 << 5)
	createTerminalOrderShippingAddressFieldPostalCode    = big.NewInt(1 << 6)
	createTerminalOrderShippingAddressFieldEmail         = big.NewInt(1 << 7)
	createTerminalOrderShippingAddressFieldPhone         = big.NewInt(1 << 8)
)

type CreateTerminalOrderShippingAddress struct {
	// Name of the person receiving the shipment.
	RecipientName string `json:"recipientName" url:"recipientName"`
	// Name of the business receiving the shipment.
	BusinessName *string `json:"businessName,omitempty" url:"businessName,omitempty"`
	// First line of the shipment address.
	AddressLine1 string `json:"addressLine1" url:"addressLine1"`
	// Second line of the shipment address.
	AddressLine2 *string `json:"addressLine2,omitempty" url:"addressLine2,omitempty"`
	// City of the shipment address.
	City string `json:"city" url:"city"`
	// State of the shipment address.
	State string `json:"state" url:"state"`
	// Postal code of the shipment address.
	PostalCode string `json:"postalCode" url:"postalCode"`
	// Contact email address for the shipment.
	Email string `json:"email" url:"email"`
	// Contact number for the shipment.
	Phone *string `json:"phone,omitempty" url:"phone,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateTerminalOrderShippingAddress) GetRecipientName() string {
	if c == nil {
		return ""
	}
	return c.RecipientName
}

func (c *CreateTerminalOrderShippingAddress) GetBusinessName() *string {
	if c == nil {
		return nil
	}
	return c.BusinessName
}

func (c *CreateTerminalOrderShippingAddress) GetAddressLine1() string {
	if c == nil {
		return ""
	}
	return c.AddressLine1
}

func (c *CreateTerminalOrderShippingAddress) GetAddressLine2() *string {
	if c == nil {
		return nil
	}
	return c.AddressLine2
}

func (c *CreateTerminalOrderShippingAddress) GetCity() string {
	if c == nil {
		return ""
	}
	return c.City
}

func (c *CreateTerminalOrderShippingAddress) GetState() string {
	if c == nil {
		return ""
	}
	return c.State
}

func (c *CreateTerminalOrderShippingAddress) GetPostalCode() string {
	if c == nil {
		return ""
	}
	return c.PostalCode
}

func (c *CreateTerminalOrderShippingAddress) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CreateTerminalOrderShippingAddress) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *CreateTerminalOrderShippingAddress) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateTerminalOrderShippingAddress) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetRecipientName sets the RecipientName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetRecipientName(recipientName string) {
	c.RecipientName = recipientName
	c.require(createTerminalOrderShippingAddressFieldRecipientName)
}

// SetBusinessName sets the BusinessName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetBusinessName(businessName *string) {
	c.BusinessName = businessName
	c.require(createTerminalOrderShippingAddressFieldBusinessName)
}

// SetAddressLine1 sets the AddressLine1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetAddressLine1(addressLine1 string) {
	c.AddressLine1 = addressLine1
	c.require(createTerminalOrderShippingAddressFieldAddressLine1)
}

// SetAddressLine2 sets the AddressLine2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetAddressLine2(addressLine2 *string) {
	c.AddressLine2 = addressLine2
	c.require(createTerminalOrderShippingAddressFieldAddressLine2)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetCity(city string) {
	c.City = city
	c.require(createTerminalOrderShippingAddressFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetState(state string) {
	c.State = state
	c.require(createTerminalOrderShippingAddressFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetPostalCode(postalCode string) {
	c.PostalCode = postalCode
	c.require(createTerminalOrderShippingAddressFieldPostalCode)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetEmail(email string) {
	c.Email = email
	c.require(createTerminalOrderShippingAddressFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingAddress) SetPhone(phone *string) {
	c.Phone = phone
	c.require(createTerminalOrderShippingAddressFieldPhone)
}

func (c *CreateTerminalOrderShippingAddress) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTerminalOrderShippingAddress
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTerminalOrderShippingAddress(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTerminalOrderShippingAddress) MarshalJSON() ([]byte, error) {
	type embed CreateTerminalOrderShippingAddress
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateTerminalOrderShippingAddress) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Object that contains the shipping preferences for the terminal order.
var (
	createTerminalOrderShippingPreferencesFieldMethod           = big.NewInt(1 << 0)
	createTerminalOrderShippingPreferencesFieldSaturdayDelivery = big.NewInt(1 << 1)
)

type CreateTerminalOrderShippingPreferences struct {
	// Shipping method for the terminal order. Send one of the following values:
	//   - `nextDay` - We schedule the order to be delivered the next day.
	//   - `ground` - We ship the order with ground shipping.
	Method *CreateTerminalOrderShippingPreferencesMethod `json:"method,omitempty" url:"method,omitempty"`
	// Indicates if we can schedule the terminal order to be delivered on a Saturday.
	SaturdayDelivery *bool `json:"saturdayDelivery,omitempty" url:"saturdayDelivery,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateTerminalOrderShippingPreferences) GetMethod() *CreateTerminalOrderShippingPreferencesMethod {
	if c == nil {
		return nil
	}
	return c.Method
}

func (c *CreateTerminalOrderShippingPreferences) GetSaturdayDelivery() *bool {
	if c == nil {
		return nil
	}
	return c.SaturdayDelivery
}

func (c *CreateTerminalOrderShippingPreferences) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateTerminalOrderShippingPreferences) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingPreferences) SetMethod(method *CreateTerminalOrderShippingPreferencesMethod) {
	c.Method = method
	c.require(createTerminalOrderShippingPreferencesFieldMethod)
}

// SetSaturdayDelivery sets the SaturdayDelivery field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTerminalOrderShippingPreferences) SetSaturdayDelivery(saturdayDelivery *bool) {
	c.SaturdayDelivery = saturdayDelivery
	c.require(createTerminalOrderShippingPreferencesFieldSaturdayDelivery)
}

func (c *CreateTerminalOrderShippingPreferences) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTerminalOrderShippingPreferences
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTerminalOrderShippingPreferences(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTerminalOrderShippingPreferences) MarshalJSON() ([]byte, error) {
	type embed CreateTerminalOrderShippingPreferences
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateTerminalOrderShippingPreferences) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Shipping method for the terminal order. Send one of the following values:
//   - `nextDay` - We schedule the order to be delivered the next day.
//   - `ground` - We ship the order with ground shipping.
type CreateTerminalOrderShippingPreferencesMethod string

const (
	CreateTerminalOrderShippingPreferencesMethodNextDay CreateTerminalOrderShippingPreferencesMethod = "nextDay"
	CreateTerminalOrderShippingPreferencesMethodGround  CreateTerminalOrderShippingPreferencesMethod = "ground"
)

func NewCreateTerminalOrderShippingPreferencesMethodFromString(s string) (CreateTerminalOrderShippingPreferencesMethod, error) {
	switch s {
	case "nextDay":
		return CreateTerminalOrderShippingPreferencesMethodNextDay, nil
	case "ground":
		return CreateTerminalOrderShippingPreferencesMethodGround, nil
	}
	var t CreateTerminalOrderShippingPreferencesMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateTerminalOrderShippingPreferencesMethod) Ptr() *CreateTerminalOrderShippingPreferencesMethod {
	return &c
}

type GetProcessingAccountPricingAgreementProcessingAccountsResponse struct {
	PricingAgreementUs40 *papisdkgo.PricingAgreementUs40
	PricingAgreementUs50 *papisdkgo.PricingAgreementUs50

	typ string
}

func (g *GetProcessingAccountPricingAgreementProcessingAccountsResponse) GetPricingAgreementUs40() *papisdkgo.PricingAgreementUs40 {
	if g == nil {
		return nil
	}
	return g.PricingAgreementUs40
}

func (g *GetProcessingAccountPricingAgreementProcessingAccountsResponse) GetPricingAgreementUs50() *papisdkgo.PricingAgreementUs50 {
	if g == nil {
		return nil
	}
	return g.PricingAgreementUs50
}

func (g *GetProcessingAccountPricingAgreementProcessingAccountsResponse) UnmarshalJSON(data []byte) error {
	valuePricingAgreementUs40 := new(papisdkgo.PricingAgreementUs40)
	if err := json.Unmarshal(data, &valuePricingAgreementUs40); err == nil {
		g.typ = "PricingAgreementUs40"
		g.PricingAgreementUs40 = valuePricingAgreementUs40
		return nil
	}
	valuePricingAgreementUs50 := new(papisdkgo.PricingAgreementUs50)
	if err := json.Unmarshal(data, &valuePricingAgreementUs50); err == nil {
		g.typ = "PricingAgreementUs50"
		g.PricingAgreementUs50 = valuePricingAgreementUs50
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetProcessingAccountPricingAgreementProcessingAccountsResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "PricingAgreementUs40" || g.PricingAgreementUs40 != nil {
		return json.Marshal(g.PricingAgreementUs40)
	}
	if g.typ == "PricingAgreementUs50" || g.PricingAgreementUs50 != nil {
		return json.Marshal(g.PricingAgreementUs50)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetProcessingAccountPricingAgreementProcessingAccountsResponseVisitor interface {
	VisitPricingAgreementUs40(*papisdkgo.PricingAgreementUs40) error
	VisitPricingAgreementUs50(*papisdkgo.PricingAgreementUs50) error
}

func (g *GetProcessingAccountPricingAgreementProcessingAccountsResponse) Accept(visitor GetProcessingAccountPricingAgreementProcessingAccountsResponseVisitor) error {
	if g.typ == "PricingAgreementUs40" || g.PricingAgreementUs40 != nil {
		return visitor.VisitPricingAgreementUs40(g.PricingAgreementUs40)
	}
	if g.typ == "PricingAgreementUs50" || g.PricingAgreementUs50 != nil {
		return visitor.VisitPricingAgreementUs50(g.PricingAgreementUs50)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}

// Filter terminal orders by status.
type ListTerminalOrdersProcessingAccountsRequestStatus string

const (
	ListTerminalOrdersProcessingAccountsRequestStatusOpen       ListTerminalOrdersProcessingAccountsRequestStatus = "open"
	ListTerminalOrdersProcessingAccountsRequestStatusHeld       ListTerminalOrdersProcessingAccountsRequestStatus = "held"
	ListTerminalOrdersProcessingAccountsRequestStatusDispatched ListTerminalOrdersProcessingAccountsRequestStatus = "dispatched"
	ListTerminalOrdersProcessingAccountsRequestStatusFulfilled  ListTerminalOrdersProcessingAccountsRequestStatus = "fulfilled"
	ListTerminalOrdersProcessingAccountsRequestStatusCancelled  ListTerminalOrdersProcessingAccountsRequestStatus = "cancelled"
)

func NewListTerminalOrdersProcessingAccountsRequestStatusFromString(s string) (ListTerminalOrdersProcessingAccountsRequestStatus, error) {
	switch s {
	case "open":
		return ListTerminalOrdersProcessingAccountsRequestStatusOpen, nil
	case "held":
		return ListTerminalOrdersProcessingAccountsRequestStatusHeld, nil
	case "dispatched":
		return ListTerminalOrdersProcessingAccountsRequestStatusDispatched, nil
	case "fulfilled":
		return ListTerminalOrdersProcessingAccountsRequestStatusFulfilled, nil
	case "cancelled":
		return ListTerminalOrdersProcessingAccountsRequestStatusCancelled, nil
	}
	var t ListTerminalOrdersProcessingAccountsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListTerminalOrdersProcessingAccountsRequestStatus) Ptr() *ListTerminalOrdersProcessingAccountsRequestStatus {
	return &l
}
