// Code generated by Fern. DO NOT EDIT.

package paymentfeatures

import (
	json "encoding/json"
	fmt "fmt"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	internal "github.com/payroc/payroc-sdk-go/internal"
	big "math/big"
)

// Object that contains information about the bank account.
type BankAccountVerificationRequestBankAccount struct {
	Type string
	Ach  *papisdkgo.AchPayload
	Pad  *papisdkgo.PadPayload
}

func (b *BankAccountVerificationRequestBankAccount) GetType() string {
	if b == nil {
		return ""
	}
	return b.Type
}

func (b *BankAccountVerificationRequestBankAccount) GetAch() *papisdkgo.AchPayload {
	if b == nil {
		return nil
	}
	return b.Ach
}

func (b *BankAccountVerificationRequestBankAccount) GetPad() *papisdkgo.PadPayload {
	if b == nil {
		return nil
	}
	return b.Pad
}

func (b *BankAccountVerificationRequestBankAccount) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	b.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", b)
	}
	switch unmarshaler.Type {
	case "ach":
		value := new(papisdkgo.AchPayload)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		b.Ach = value
	case "pad":
		value := new(papisdkgo.PadPayload)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		b.Pad = value
	}
	return nil
}

func (b BankAccountVerificationRequestBankAccount) MarshalJSON() ([]byte, error) {
	if err := b.validate(); err != nil {
		return nil, err
	}
	if b.Ach != nil {
		return internal.MarshalJSONWithExtraProperty(b.Ach, "type", "ach")
	}
	if b.Pad != nil {
		return internal.MarshalJSONWithExtraProperty(b.Pad, "type", "pad")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", b)
}

type BankAccountVerificationRequestBankAccountVisitor interface {
	VisitAch(*papisdkgo.AchPayload) error
	VisitPad(*papisdkgo.PadPayload) error
}

func (b *BankAccountVerificationRequestBankAccount) Accept(visitor BankAccountVerificationRequestBankAccountVisitor) error {
	if b.Ach != nil {
		return visitor.VisitAch(b.Ach)
	}
	if b.Pad != nil {
		return visitor.VisitPad(b.Pad)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", b)
}

func (b *BankAccountVerificationRequestBankAccount) validate() error {
	if b == nil {
		return fmt.Errorf("type %T is nil", b)
	}
	var fields []string
	if b.Ach != nil {
		fields = append(fields, "ach")
	}
	if b.Pad != nil {
		fields = append(fields, "pad")
	}
	if len(fields) == 0 {
		if b.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", b, b.Type)
		}
		return fmt.Errorf("type %T is empty", b)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", b, fields)
	}
	if b.Type != "" {
		field := fields[0]
		if b.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				b,
				b.Type,
				b,
			)
		}
	}
	return nil
}

var (
	bankAccountVerificationRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	bankAccountVerificationRequestFieldProcessingTerminalId = big.NewInt(1 << 1)
	bankAccountVerificationRequestFieldBankAccount          = big.NewInt(1 << 2)
)

type BankAccountVerificationRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"processingTerminalId" url:"-"`
	// Object that contains information about the bank account.
	BankAccount *BankAccountVerificationRequestBankAccount `json:"bankAccount,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BankAccountVerificationRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationRequest) SetIdempotencyKey(idempotencyKey string) {
	b.IdempotencyKey = idempotencyKey
	b.require(bankAccountVerificationRequestFieldIdempotencyKey)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationRequest) SetProcessingTerminalId(processingTerminalId string) {
	b.ProcessingTerminalId = processingTerminalId
	b.require(bankAccountVerificationRequestFieldProcessingTerminalId)
}

// SetBankAccount sets the BankAccount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationRequest) SetBankAccount(bankAccount *BankAccountVerificationRequestBankAccount) {
	b.BankAccount = bankAccount
	b.require(bankAccountVerificationRequestFieldBankAccount)
}
