// Code generated by Fern. DO NOT EDIT.

package refunds

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	banktransferpayments "github.com/payroc/payroc-sdk-go/banktransferpayments"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) ReversePayment(
	ctx context.Context,
	request *banktransferpayments.ReversePaymentRefundsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.BankTransferPayment], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/bank-transfer-payments/%v/reverse",
		request.PaymentId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *payroc.BankTransferPayment
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.BankTransferPayment]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Refund(
	ctx context.Context,
	request *banktransferpayments.BankTransferReferencedRefund,
	opts ...option.RequestOption,
) (*core.Response[*payroc.BankTransferPayment], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/bank-transfer-payments/%v/refund",
		request.PaymentId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *payroc.BankTransferPayment
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.BankTransferPayment]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) List(
	ctx context.Context,
	request *banktransferpayments.ListRefundsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.BankTransferRefundPaginatedList], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/bank-transfer-refunds"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.BankTransferRefundPaginatedList
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.BankTransferRefundPaginatedList]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *banktransferpayments.BankTransferUnreferencedRefund,
	opts ...option.RequestOption,
) (*core.Response[*payroc.BankTransferRefund], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/bank-transfer-refunds"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *payroc.BankTransferRefund
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.BankTransferRefund]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Retrieve(
	ctx context.Context,
	request *banktransferpayments.RetrieveRefundsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.BankTransferRefund], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/bank-transfer-refunds/%v",
		request.RefundId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.BankTransferRefund
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.BankTransferRefund]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ReverseRefund(
	ctx context.Context,
	request *banktransferpayments.ReverseRefundRefundsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.BankTransferRefund], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/bank-transfer-refunds/%v/reverse",
		request.RefundId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	var response *payroc.BankTransferRefund
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.BankTransferRefund]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
