// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	request *payroc.ListPaymentLinksRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.PaymentLinkPaginatedList], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-terminals/%v/payment-links",
		request.ProcessingTerminalId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.PaymentLinkPaginatedList
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.PaymentLinkPaginatedList]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *payroc.CreatePaymentLinksRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.CreatePaymentLinksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-terminals/%v/payment-links",
		request.ProcessingTerminalId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *payroc.CreatePaymentLinksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.CreatePaymentLinksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Retrieve(
	ctx context.Context,
	request *payroc.RetrievePaymentLinksRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.RetrievePaymentLinksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/payment-links/%v",
		request.PaymentLinkId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.RetrievePaymentLinksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.RetrievePaymentLinksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PartiallyUpdate(
	ctx context.Context,
	request *payroc.PartiallyUpdatePaymentLinksRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.PartiallyUpdatePaymentLinksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/payment-links/%v",
		request.PaymentLinkId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *payroc.PartiallyUpdatePaymentLinksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.PartiallyUpdatePaymentLinksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Deactivate(
	ctx context.Context,
	request *payroc.DeactivatePaymentLinksRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.DeactivatePaymentLinksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/payment-links/%v/deactivate",
		request.PaymentLinkId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.DeactivatePaymentLinksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.DeactivatePaymentLinksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
