// Code generated by Fern. DO NOT EDIT.

package payroc_cloud_signature_instructions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	client "github.com/payroc/payroc-sdk-go/client"
	option "github.com/payroc/payroc-sdk-go/option"
	payroccloud "github.com/payroc/payroc-sdk-go/payroccloud"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPayrocCloudSignatureInstructionsSubmitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payroccloud.SignatureInstructionRequest{
		SerialNumber:         "1850010868",
		IdempotencyKey:       "8e03978e-40d5-43e8-bc93-6894a57f9324",
		ProcessingTerminalId: "1234001",
	}
	_, invocationErr := client.PayrocCloud.SignatureInstructions.Submit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPayrocCloudSignatureInstructionsSubmitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPayrocCloudSignatureInstructionsSubmitWithWireMock", "POST", "/devices/1850010868/signature-instructions", nil, 1)
}

func TestPayrocCloudSignatureInstructionsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payroccloud.RetrieveSignatureInstructionsRequest{
		SignatureInstructionId: "a37439165d134678a9100ebba3b29597",
	}
	_, invocationErr := client.PayrocCloud.SignatureInstructions.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPayrocCloudSignatureInstructionsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPayrocCloudSignatureInstructionsRetrieveWithWireMock", "GET", "/signature-instructions/a37439165d134678a9100ebba3b29597", nil, 1)
}

func TestPayrocCloudSignatureInstructionsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payroccloud.DeleteSignatureInstructionsRequest{
		SignatureInstructionId: "a37439165d134678a9100ebba3b29597",
	}
	invocationErr := client.PayrocCloud.SignatureInstructions.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPayrocCloudSignatureInstructionsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPayrocCloudSignatureInstructionsDeleteWithWireMock", "DELETE", "/signature-instructions/a37439165d134678a9100ebba3b29597", nil, 1)
}
