// Code generated by Fern. DO NOT EDIT.

package processingaccounts

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	boarding "github.com/payroc/payroc-sdk-go/boarding"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) Retrieve(
	ctx context.Context,
	request *boarding.RetrieveProcessingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.ProcessingAccount], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v",
		request.ProcessingAccountId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.ProcessingAccount
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.ProcessingAccount]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListProcessingAccountFundingAccounts(
	ctx context.Context,
	request *boarding.ListProcessingAccountFundingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*payroc.FundingAccount], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/funding-accounts",
		request.ProcessingAccountId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*payroc.FundingAccount
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*payroc.FundingAccount]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListContacts(
	ctx context.Context,
	request *boarding.ListContactsProcessingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.PaginatedContacts], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/contacts",
		request.ProcessingAccountId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.PaginatedContacts
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.PaginatedContacts]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetProcessingAccountPricingAgreement(
	ctx context.Context,
	request *boarding.GetProcessingAccountPricingAgreementProcessingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*boarding.GetProcessingAccountPricingAgreementProcessingAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/pricing",
		request.ProcessingAccountId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *boarding.GetProcessingAccountPricingAgreementProcessingAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*boarding.GetProcessingAccountPricingAgreementProcessingAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListOwners(
	ctx context.Context,
	request *boarding.ListProcessingAccountOwnersRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.PaginatedOwners], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/owners",
		request.ProcessingAccountId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.PaginatedOwners
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.PaginatedOwners]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateReminder(
	ctx context.Context,
	request *boarding.CreateReminderProcessingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*boarding.CreateReminderProcessingAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/reminders",
		request.ProcessingAccountId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *boarding.CreateReminderProcessingAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*boarding.CreateReminderProcessingAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListTerminalOrders(
	ctx context.Context,
	request *boarding.ListTerminalOrdersProcessingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*payroc.TerminalOrder], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/terminal-orders",
		request.ProcessingAccountId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*payroc.TerminalOrder
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*payroc.TerminalOrder]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateTerminalOrder(
	ctx context.Context,
	request *boarding.CreateTerminalOrder,
	opts ...option.RequestOption,
) (*core.Response[*payroc.TerminalOrder], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/terminal-orders",
		request.ProcessingAccountId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *payroc.TerminalOrder
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.TerminalOrder]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListProcessingTerminals(
	ctx context.Context,
	request *boarding.ListProcessingTerminalsProcessingAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.PaginatedProcessingTerminals], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processing-accounts/%v/processing-terminals",
		request.ProcessingAccountId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.PaginatedProcessingTerminals
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(boarding.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.PaginatedProcessingTerminals]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
