// Code generated by Fern. DO NOT EDIT.

package fundingrecipients

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	core "github.com/payroc/payroc-sdk-go/core"
	funding "github.com/payroc/payroc-sdk-go/funding"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Use this method to return a [paginated](https://docs.payroc.com/api/pagination) list of funding recipients linked to your account.
//
// Note: If you want to view the details of a specific funding recipient and you have its recipientId, use our [Retrieve Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/retrieve) method.
//
// Our gateway returns the following information about each funding recipient in the list:
// - Tax ID and Doing Business As (DBA) name.
// - Address and contact details.
// - Funding accounts linked to the funding recipient.
//
// For each funding recipient, we also return the recipientId, which you can use to perform follow-on actions.
func (c *Client) List(
	ctx context.Context,
	request *funding.ListFundingRecipientsRequest,
	opts ...option.RequestOption,
) (*core.PayrocPager[*payroc.PaginatedFundRecipients, []*payroc.FundingRecipient, *payroc.Link], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		c.baseURL,
		internal.ResolveEnvironmentBaseURL(
			c.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/funding-recipients"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	response, callErr := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if callErr != nil {
		return nil, callErr
	}
	var responseBody *payroc.PaginatedFundRecipients = response.Body
	fetcher := func(
		ctx context.Context,
		href string,
	) (*payroc.PaginatedFundRecipients, error) {
		options := core.NewRequestOptions(opts...)
		headers := internal.MergeHeaders(
			c.options.ToHeader(),
			options.ToHeader(),
		)
		var pageResponse *payroc.PaginatedFundRecipients
		_, err := c.caller.Call(ctx, &internal.CallParams{
			URL:             href,
			Method:          "GET",
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &pageResponse,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		})
		if err != nil {
			return nil, err
		}
		return pageResponse, nil
	}
	pager := core.NewPayrocPager(responseBody, fetcher)
	return pager, nil
}

// Use this method to create a funding recipient.
//
// A funding recipient is a business or organization that can receive funds but can't run transactions, for example, a charity.
//
// In the request, include the following information:
// -	Legal information, including its tax ID, Doing Business As (DBA) name, and address.
// -	Contact information, including the email address.
// -	Owners' details, including their contact details.
// -	Funding account details.
//
// Our gateway returns the recipientId of the funding recipient, which you can use to run follow-on actions.
func (c *Client) Create(
	ctx context.Context,
	request *funding.CreateFundingRecipient,
	opts ...option.RequestOption,
) (*payroc.FundingRecipient, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to retrieve information about a funding recipient.
//
// To retrieve a funding recipient, you need its recipientId. Our gateway returned the recipientId in the response of the [Create Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/create) method.
//
// **Note:** If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
//
// Our gateway returns the following information about the funding recipient:
//
// - Tax ID and Doing Business As (DBA) name.
// - Address and contact details.
// - Funding accounts linked to the funding recipient.
func (c *Client) Retrieve(
	ctx context.Context,
	request *funding.RetrieveFundingRecipientsRequest,
	opts ...option.RequestOption,
) (*payroc.FundingRecipient, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to update the details of a funding recipient. If a request contains significant changes, we might need to re-approve the funding recipient.
//
// To update a funding recipient, you need it's recipientId. Our gateway returned the recipientId in the response of the [Create Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/create) method.
//
// **Note**: If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
//
// You can update the following details of a funding recipient:
// - Doing Business As (DBA) name
// - Tax ID and charity ID
// - Address and contact methods
func (c *Client) Update(
	ctx context.Context,
	request *funding.UpdateFundingRecipientsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Use this method to delete a funding recipient, including its funding accounts and owners.
//
// To delete a funding recipient, you need its recipientId. Our gateway returned the recipientId in the response of the [Create Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/create) method.
//
// **Note**: If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
func (c *Client) Delete(
	ctx context.Context,
	request *funding.DeleteFundingRecipientsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Use  this method to return a list of funding accounts associated with a funding recipient.
//
// **Note:** If you want to view the details of a specific funding account and you have its fundingAccountId, use our [Retrieve Funding Account](https://docs.payroc.com/api/schema/funding/funding-accounts/retrieve) method.
//
// To retrieve the funding accounts associated with a funding recipient, you need the recipientId. If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
//
// Our gateway returns the following information about each funding account:
// -	Name of the account holder.
// -	ACH details for the account.
// -	Status of the account.
//
// Our gateway also returns the fundingAccountId, which you can use to run follow-on actions.
func (c *Client) ListAccounts(
	ctx context.Context,
	request *funding.ListFundingRecipientFundingAccountsRequest,
	opts ...option.RequestOption,
) ([]*payroc.FundingAccount, error) {
	response, err := c.WithRawResponse.ListAccounts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to create a funding account and add it to a funding recipient.
//
// To add a funding account to a funding recipient, you need the recipientId. Our gateway returned the recipientId in the response of the [Create Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/create) method.
//
// **Note:** If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
//
// In the request, include the following information:
// -	Account type, for example, if the account is a checking or savings account.
// -	Account holder's name.
// -	ACH information, including the routing number and account number of the account.
//
// Our gateway returns the fundingAccountId, which you can use to run follow-on actions.
func (c *Client) CreateAccount(
	ctx context.Context,
	request *funding.CreateAccountFundingRecipientsRequest,
	opts ...option.RequestOption,
) (*payroc.FundingAccount, error) {
	response, err := c.WithRawResponse.CreateAccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to return a list of owners of a funding recipient.
//
// **Note:** If you want to view the details of a specific owner and you have their ownerId, use our [Retrieve Owner](https://docs.payroc.com/api/schema/boarding/owners/retrieve) method.
//
// To list the owners of a funding recipient, you need its recipientId. Our gateway returned the recipientId in the response of the [Create Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/create) method. If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
//
// Our gateway returns the following information about each owner in the list:
// -	Name, date of birth, and address.
// -	Contact details, including their email address.
// -	Relationship to the funding recipient.
//
// Our gateway also returns the ownerId, which you can use to perform follow-on actions.
func (c *Client) ListOwners(
	ctx context.Context,
	request *funding.ListFundingRecipientOwnersRequest,
	opts ...option.RequestOption,
) ([]*payroc.Owner, error) {
	response, err := c.WithRawResponse.ListOwners(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to add an additional owner to a funding recipient.
//
// To add an owner to a funding recipient, you need the recipientId. Our gateway returned the recipientId in the response of the [Create Funding Recipient](https://docs.payroc.com/api/schema/funding/funding-recipients/create) method.
//
// **Note:** If you don't have the recipientId, use our [List Funding Recipients](https://docs.payroc.com/api/schema/funding/funding-recipients/list) method to search for the funding recipient.
//
// In the request, include the following information about the owner:
//
// - Name, date of birth, and address.
// - Contact details, including their email address.
// - Relationship to the funding recipient, including whether they are a control prong.
//
// In the response, our gateway returns the ownerId, which you can use to run follow-on actions.
func (c *Client) CreateOwner(
	ctx context.Context,
	request *funding.CreateOwnerFundingRecipientsRequest,
	opts ...option.RequestOption,
) (*payroc.Owner, error) {
	response, err := c.WithRawResponse.CreateOwner(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
