// Code generated by Fern. DO NOT EDIT.

package boarding_owners_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payroc "github.com/payroc/payroc-sdk-go"
	boarding "github.com/payroc/payroc-sdk-go/boarding"
	client "github.com/payroc/payroc-sdk-go/client"
	option "github.com/payroc/payroc-sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestBoardingOwnersRetrieveWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewPayrocClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &boarding.RetrieveOwnersRequest{
		OwnerId: 1,
	}
	_, invocationErr := client.Boarding.Owners.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBoardingOwnersRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBoardingOwnersRetrieveWithWireMock", "GET", "/owners/1", nil, 1)
}

func TestBoardingOwnersUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewPayrocClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &boarding.UpdateOwnersRequest{
		OwnerId: 1,
		Body: &payroc.Owner{
			FirstName: "Jane",
			MiddleName: payroc.String(
				"Helen",
			),
			LastName: "Doe",
			DateOfBirth: payroc.MustParseDate(
				"1964-03-22",
			),
			Address: &payroc.Address{
				Address1: "1 Example Ave.",
				Address2: payroc.String(
					"Example Address Line 2",
				),
				Address3: payroc.String(
					"Example Address Line 3",
				),
				City:       "Chicago",
				State:      "Illinois",
				Country:    "US",
				PostalCode: "60056",
			},
			Identifiers: []*payroc.Identifier{
				&payroc.Identifier{
					Type:  payroc.IdentifierTypeNationalId,
					Value: "000-00-4320",
				},
			},
			ContactMethods: []*payroc.ContactMethod{
				&payroc.ContactMethod{
					Email: &payroc.ContactMethodEmail{
						Value: "jane.doe@example.com",
					},
				},
			},
			Relationship: &payroc.OwnerRelationship{
				EquityPercentage: payroc.Float64(
					48.5,
				),
				Title: payroc.String(
					"CFO",
				),
				IsControlProng: true,
				IsAuthorizedSignatory: payroc.Bool(
					false,
				),
			},
		},
	}
	invocationErr := client.Boarding.Owners.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBoardingOwnersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBoardingOwnersUpdateWithWireMock", "PUT", "/owners/1", nil, 1)
}

func TestBoardingOwnersDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewPayrocClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &boarding.DeleteOwnersRequest{
		OwnerId: 1,
	}
	invocationErr := client.Boarding.Owners.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBoardingOwnersDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBoardingOwnersDeleteWithWireMock", "DELETE", "/owners/1", nil, 1)
}
