// Code generated by Fern. DO NOT EDIT.

package paymentlinks

import (
	json "encoding/json"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	big "math/big"
)

var (
	listSharingEventsRequestFieldPaymentLinkId  = big.NewInt(1 << 0)
	listSharingEventsRequestFieldRecipientName  = big.NewInt(1 << 1)
	listSharingEventsRequestFieldRecipientEmail = big.NewInt(1 << 2)
	listSharingEventsRequestFieldBefore         = big.NewInt(1 << 3)
	listSharingEventsRequestFieldAfter          = big.NewInt(1 << 4)
	listSharingEventsRequestFieldLimit          = big.NewInt(1 << 5)
)

type ListSharingEventsRequest struct {
	// Unique identifier that we assigned to the payment link.
	PaymentLinkId string `json:"-" url:"-"`
	// Filter results by the customer's name.
	RecipientName *string `json:"-" url:"recipientName,omitempty"`
	// Filter results by the customer's email address.
	RecipientEmail *string `json:"-" url:"recipientEmail,omitempty"`
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSharingEventsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPaymentLinkId sets the PaymentLinkId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSharingEventsRequest) SetPaymentLinkId(paymentLinkId string) {
	l.PaymentLinkId = paymentLinkId
	l.require(listSharingEventsRequestFieldPaymentLinkId)
}

// SetRecipientName sets the RecipientName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSharingEventsRequest) SetRecipientName(recipientName *string) {
	l.RecipientName = recipientName
	l.require(listSharingEventsRequestFieldRecipientName)
}

// SetRecipientEmail sets the RecipientEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSharingEventsRequest) SetRecipientEmail(recipientEmail *string) {
	l.RecipientEmail = recipientEmail
	l.require(listSharingEventsRequestFieldRecipientEmail)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSharingEventsRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listSharingEventsRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSharingEventsRequest) SetAfter(after *string) {
	l.After = after
	l.require(listSharingEventsRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSharingEventsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listSharingEventsRequestFieldLimit)
}

var (
	shareSharingEventsRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	shareSharingEventsRequestFieldPaymentLinkId  = big.NewInt(1 << 1)
)

type ShareSharingEventsRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the payment link.
	PaymentLinkId string                                `json:"-" url:"-"`
	Body          *papisdkgo.PaymentLinkEmailShareEvent `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShareSharingEventsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShareSharingEventsRequest) SetIdempotencyKey(idempotencyKey string) {
	s.IdempotencyKey = idempotencyKey
	s.require(shareSharingEventsRequestFieldIdempotencyKey)
}

// SetPaymentLinkId sets the PaymentLinkId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShareSharingEventsRequest) SetPaymentLinkId(paymentLinkId string) {
	s.PaymentLinkId = paymentLinkId
	s.require(shareSharingEventsRequestFieldPaymentLinkId)
}

func (s *ShareSharingEventsRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.PaymentLinkEmailShareEvent)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.Body = body
	return nil
}

func (s *ShareSharingEventsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}
