// Code generated by Fern. DO NOT EDIT.

package client

import (
	contacts "github.com/payroc/payroc-sdk-go/boarding/contacts"
	merchantplatforms "github.com/payroc/payroc-sdk-go/boarding/merchantplatforms"
	owners "github.com/payroc/payroc-sdk-go/boarding/owners"
	pricingintents "github.com/payroc/payroc-sdk-go/boarding/pricingintents"
	processingaccounts "github.com/payroc/payroc-sdk-go/boarding/processingaccounts"
	processingterminals "github.com/payroc/payroc-sdk-go/boarding/processingterminals"
	terminalorders "github.com/payroc/payroc-sdk-go/boarding/terminalorders"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
)

type Client struct {
	Owners              *owners.Client
	PricingIntents      *pricingintents.Client
	MerchantPlatforms   *merchantplatforms.Client
	ProcessingAccounts  *processingaccounts.Client
	ProcessingTerminals *processingterminals.Client
	Contacts            *contacts.Client
	TerminalOrders      *terminalorders.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Owners:              owners.NewClient(options),
		PricingIntents:      pricingintents.NewClient(options),
		MerchantPlatforms:   merchantplatforms.NewClient(options),
		ProcessingAccounts:  processingaccounts.NewClient(options),
		ProcessingTerminals: processingterminals.NewClient(options),
		Contacts:            contacts.NewClient(options),
		TerminalOrders:      terminalorders.NewClient(options),
		options:             options,
		baseURL:             options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
