// Code generated by Fern. DO NOT EDIT.

package refundinstructions

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	payroccloud "github.com/payroc/payroc-sdk-go/payroccloud"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Use this method to submit an instruction request to initiate a refund on a payment device.
//
// In the request, include the refund amount and currency.
//
// If the request is successful, our gateway returns information about the refund instruction and a refundInstructionId, which you need for the following methods:
// - [Retrieve refund instruction](https://docs.payroc.com/api/schema/payroc-cloud/refund-instructions/retrieve) - View the details of the refund instruction.
// - [Cancel refund instruction](https://docs.payroc.com/api/schema/payroc-cloud/refund-instructions/delete) - Cancel the refund instruction.
func (c *Client) Submit(
	ctx context.Context,
	request *payroccloud.RefundInstructionRequest,
	opts ...option.RequestOption,
) (*payroc.RefundInstruction, error) {
	response, err := c.WithRawResponse.Submit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to retrieve information about a refund instruction.
//
// To retrieve a refund instruction, you need its refundInstructionId. Our gateway returned the refundInstructionId in the response of the [Submit Refund Instruction](https://docs.payroc.com/api/schema/payroc-cloud/refund-instructions/submit) method.
//
// Our gateway returns the status of the refund instruction. If the payment device completed the refund instruction, the response also includes a link to the refund.
func (c *Client) Retrieve(
	ctx context.Context,
	request *payroccloud.RetrieveRefundInstructionsRequest,
	opts ...option.RequestOption,
) (*payroc.RefundInstruction, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to cancel a refund instruction.
//
// You can cancel a refund instruction only if its status is `inProgress`. To retrieve the status of a refund instruction, use our [Retrieve Refund Instruction](https://docs.payroc.com/api/schema/payroc-cloud/refund-instructions/retrieve) method.
//
// To cancel a refund instruction, you need its refundInstructionId. Our gateway returned the refundInstructionId in the response of the [Submit Refund Instruction](https://docs.payroc.com/api/schema/payroc-cloud/refund-instructions/submit) method.
func (c *Client) Delete(
	ctx context.Context,
	request *payroccloud.DeleteRefundInstructionsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
