// Code generated by Fern. DO NOT EDIT.

package funding

import (
	json "encoding/json"
	fmt "fmt"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	internal "github.com/payroc/payroc-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	listFundingActivityRequestFieldBefore     = big.NewInt(1 << 0)
	listFundingActivityRequestFieldAfter      = big.NewInt(1 << 1)
	listFundingActivityRequestFieldLimit      = big.NewInt(1 << 2)
	listFundingActivityRequestFieldDateFrom   = big.NewInt(1 << 3)
	listFundingActivityRequestFieldDateTo     = big.NewInt(1 << 4)
	listFundingActivityRequestFieldMerchantId = big.NewInt(1 << 5)
)

type ListFundingActivityRequest struct {
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter by activity after a specific date. Send a value in **YYYY-MM-DD** format.
	DateFrom time.Time `json:"-" url:"dateFrom" format:"date"`
	// Filter by activity before a specific date. Send a value in **YYYY-MM-DD** format.
	DateTo time.Time `json:"-" url:"dateTo" format:"date"`
	// Filter results by the unique identifier that the processor assigned to the merchant.
	MerchantId *string `json:"-" url:"merchantId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFundingActivityRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listFundingActivityRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityRequest) SetAfter(after *string) {
	l.After = after
	l.require(listFundingActivityRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFundingActivityRequestFieldLimit)
}

// SetDateFrom sets the DateFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityRequest) SetDateFrom(dateFrom time.Time) {
	l.DateFrom = dateFrom
	l.require(listFundingActivityRequestFieldDateFrom)
}

// SetDateTo sets the DateTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityRequest) SetDateTo(dateTo time.Time) {
	l.DateTo = dateTo
	l.require(listFundingActivityRequestFieldDateTo)
}

// SetMerchantId sets the MerchantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityRequest) SetMerchantId(merchantId *string) {
	l.MerchantId = merchantId
	l.require(listFundingActivityRequestFieldMerchantId)
}

var (
	retrieveBalanceFundingActivityRequestFieldBefore     = big.NewInt(1 << 0)
	retrieveBalanceFundingActivityRequestFieldAfter      = big.NewInt(1 << 1)
	retrieveBalanceFundingActivityRequestFieldLimit      = big.NewInt(1 << 2)
	retrieveBalanceFundingActivityRequestFieldMerchantId = big.NewInt(1 << 3)
)

type RetrieveBalanceFundingActivityRequest struct {
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter results by the unique identifier that the processor assigned to the merchant.
	MerchantId *string `json:"-" url:"merchantId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveBalanceFundingActivityRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityRequest) SetBefore(before *string) {
	r.Before = before
	r.require(retrieveBalanceFundingActivityRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityRequest) SetAfter(after *string) {
	r.After = after
	r.require(retrieveBalanceFundingActivityRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityRequest) SetLimit(limit *int) {
	r.Limit = limit
	r.require(retrieveBalanceFundingActivityRequestFieldLimit)
}

// SetMerchantId sets the MerchantId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityRequest) SetMerchantId(merchantId *string) {
	r.MerchantId = merchantId
	r.require(retrieveBalanceFundingActivityRequestFieldMerchantId)
}

var (
	listFundingActivityResponseFieldLimit   = big.NewInt(1 << 0)
	listFundingActivityResponseFieldCount   = big.NewInt(1 << 1)
	listFundingActivityResponseFieldHasMore = big.NewInt(1 << 2)
	listFundingActivityResponseFieldLinks   = big.NewInt(1 << 3)
	listFundingActivityResponseFieldData    = big.NewInt(1 << 4)
)

type ListFundingActivityResponse struct {
	// Maximum number of results that we return for each page.
	Limit *float64 `json:"limit,omitempty" url:"limit,omitempty"`
	// Number of results we returned on this page.
	//
	// **Note:** This might not be the total number of results that match your query.
	Count *float64 `json:"count,omitempty" url:"count,omitempty"`
	// Indicates whether there is another page of results available.
	HasMore *bool `json:"hasMore,omitempty" url:"hasMore,omitempty"`
	// Reference links to navigate to the previous page of results or to the next page of results.
	Links []*papisdkgo.Link `json:"links,omitempty" url:"links,omitempty"`
	// Array of activityRecord objects.
	Data []*papisdkgo.ActivityRecord `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListFundingActivityResponse) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListFundingActivityResponse) GetCount() *float64 {
	if l == nil {
		return nil
	}
	return l.Count
}

func (l *ListFundingActivityResponse) GetHasMore() *bool {
	if l == nil {
		return nil
	}
	return l.HasMore
}

func (l *ListFundingActivityResponse) GetLinks() []*papisdkgo.Link {
	if l == nil {
		return nil
	}
	return l.Links
}

func (l *ListFundingActivityResponse) GetData() []*papisdkgo.ActivityRecord {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListFundingActivityResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListFundingActivityResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityResponse) SetLimit(limit *float64) {
	l.Limit = limit
	l.require(listFundingActivityResponseFieldLimit)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityResponse) SetCount(count *float64) {
	l.Count = count
	l.require(listFundingActivityResponseFieldCount)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityResponse) SetHasMore(hasMore *bool) {
	l.HasMore = hasMore
	l.require(listFundingActivityResponseFieldHasMore)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityResponse) SetLinks(links []*papisdkgo.Link) {
	l.Links = links
	l.require(listFundingActivityResponseFieldLinks)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingActivityResponse) SetData(data []*papisdkgo.ActivityRecord) {
	l.Data = data
	l.require(listFundingActivityResponseFieldData)
}

func (l *ListFundingActivityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListFundingActivityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListFundingActivityResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListFundingActivityResponse) MarshalJSON() ([]byte, error) {
	type embed ListFundingActivityResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListFundingActivityResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	retrieveBalanceFundingActivityResponseFieldLimit   = big.NewInt(1 << 0)
	retrieveBalanceFundingActivityResponseFieldCount   = big.NewInt(1 << 1)
	retrieveBalanceFundingActivityResponseFieldHasMore = big.NewInt(1 << 2)
	retrieveBalanceFundingActivityResponseFieldLinks   = big.NewInt(1 << 3)
	retrieveBalanceFundingActivityResponseFieldData    = big.NewInt(1 << 4)
)

type RetrieveBalanceFundingActivityResponse struct {
	// Maximum number of results that we return for each page.
	Limit *float64 `json:"limit,omitempty" url:"limit,omitempty"`
	// Number of results we returned on this page.
	//
	// **Note:** This might not be the total number of results that match your query.
	Count *float64 `json:"count,omitempty" url:"count,omitempty"`
	// Indicates whether there is another page of results available.
	HasMore *bool `json:"hasMore,omitempty" url:"hasMore,omitempty"`
	// Reference links to navigate to the previous page of results or to the next page of results.
	Links []*papisdkgo.Link `json:"links,omitempty" url:"links,omitempty"`
	// Array of merchantBalance objects.
	Data []*papisdkgo.MerchantBalance `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveBalanceFundingActivityResponse) GetLimit() *float64 {
	if r == nil {
		return nil
	}
	return r.Limit
}

func (r *RetrieveBalanceFundingActivityResponse) GetCount() *float64 {
	if r == nil {
		return nil
	}
	return r.Count
}

func (r *RetrieveBalanceFundingActivityResponse) GetHasMore() *bool {
	if r == nil {
		return nil
	}
	return r.HasMore
}

func (r *RetrieveBalanceFundingActivityResponse) GetLinks() []*papisdkgo.Link {
	if r == nil {
		return nil
	}
	return r.Links
}

func (r *RetrieveBalanceFundingActivityResponse) GetData() []*papisdkgo.MerchantBalance {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RetrieveBalanceFundingActivityResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveBalanceFundingActivityResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityResponse) SetLimit(limit *float64) {
	r.Limit = limit
	r.require(retrieveBalanceFundingActivityResponseFieldLimit)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityResponse) SetCount(count *float64) {
	r.Count = count
	r.require(retrieveBalanceFundingActivityResponseFieldCount)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityResponse) SetHasMore(hasMore *bool) {
	r.HasMore = hasMore
	r.require(retrieveBalanceFundingActivityResponseFieldHasMore)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityResponse) SetLinks(links []*papisdkgo.Link) {
	r.Links = links
	r.require(retrieveBalanceFundingActivityResponseFieldLinks)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveBalanceFundingActivityResponse) SetData(data []*papisdkgo.MerchantBalance) {
	r.Data = data
	r.require(retrieveBalanceFundingActivityResponseFieldData)
}

func (r *RetrieveBalanceFundingActivityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveBalanceFundingActivityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveBalanceFundingActivityResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveBalanceFundingActivityResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveBalanceFundingActivityResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveBalanceFundingActivityResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
