// Code generated by Fern. DO NOT EDIT.

package funding

import (
	json "encoding/json"
	fmt "fmt"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	internal "github.com/payroc/payroc-sdk-go/internal"
	big "math/big"
)

var (
	createFundingRecipientFieldIdempotencyKey  = big.NewInt(1 << 0)
	createFundingRecipientFieldRecipientType   = big.NewInt(1 << 1)
	createFundingRecipientFieldTaxId           = big.NewInt(1 << 2)
	createFundingRecipientFieldCharityId       = big.NewInt(1 << 3)
	createFundingRecipientFieldDoingBusinessAs = big.NewInt(1 << 4)
	createFundingRecipientFieldAddress         = big.NewInt(1 << 5)
	createFundingRecipientFieldContactMethods  = big.NewInt(1 << 6)
	createFundingRecipientFieldMetadata        = big.NewInt(1 << 7)
	createFundingRecipientFieldOwners          = big.NewInt(1 << 8)
	createFundingRecipientFieldFundingAccounts = big.NewInt(1 << 9)
)

type CreateFundingRecipient struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Type or legal structure of the funding recipient.
	RecipientType CreateFundingRecipientRecipientType `json:"recipientType" url:"-"`
	// Employer identification number (EIN) or Social Security number (SSN).
	TaxId string `json:"taxId" url:"-"`
	// Government identifier of the charity.
	CharityId *string `json:"charityId,omitempty" url:"-"`
	// Trading name of the business or organization.
	DoingBusinessAs string `json:"doingBusinessAs" url:"-"`
	// Polymorphic object that contains address information for a funding recipient.
	Address *papisdkgo.Address `json:"address" url:"-"`
	// Array of polymorphic objects, which contain contact information.
	//
	// **Note:** You must provide an email address.
	//
	// The value of the type parameter determines which variant you should use:
	// -	`email` - Email address
	// -	`phone` - Phone number
	// -	`mobile` - Mobile number
	// -	`fax` - Fax number
	ContactMethods []*papisdkgo.ContactMethod `json:"contactMethods" url:"-"`
	// [Metadata](https://docs.payroc.com/api/metadata) object you can use to include custom data with your request.
	Metadata map[string]string `json:"metadata,omitempty" url:"-"`
	// Array of owner objects. Each object contains information about an individual who owns or manages the funding recipient.
	Owners []*papisdkgo.Owner `json:"owners" url:"-"`
	// Array of fundingAccount objects that you can use to add funding accounts to the funding recipient.
	FundingAccounts []*papisdkgo.FundingAccount `json:"fundingAccounts" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateFundingRecipient) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createFundingRecipientFieldIdempotencyKey)
}

// SetRecipientType sets the RecipientType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetRecipientType(recipientType CreateFundingRecipientRecipientType) {
	c.RecipientType = recipientType
	c.require(createFundingRecipientFieldRecipientType)
}

// SetTaxId sets the TaxId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetTaxId(taxId string) {
	c.TaxId = taxId
	c.require(createFundingRecipientFieldTaxId)
}

// SetCharityId sets the CharityId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetCharityId(charityId *string) {
	c.CharityId = charityId
	c.require(createFundingRecipientFieldCharityId)
}

// SetDoingBusinessAs sets the DoingBusinessAs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetDoingBusinessAs(doingBusinessAs string) {
	c.DoingBusinessAs = doingBusinessAs
	c.require(createFundingRecipientFieldDoingBusinessAs)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetAddress(address *papisdkgo.Address) {
	c.Address = address
	c.require(createFundingRecipientFieldAddress)
}

// SetContactMethods sets the ContactMethods field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetContactMethods(contactMethods []*papisdkgo.ContactMethod) {
	c.ContactMethods = contactMethods
	c.require(createFundingRecipientFieldContactMethods)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetMetadata(metadata map[string]string) {
	c.Metadata = metadata
	c.require(createFundingRecipientFieldMetadata)
}

// SetOwners sets the Owners field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetOwners(owners []*papisdkgo.Owner) {
	c.Owners = owners
	c.require(createFundingRecipientFieldOwners)
}

// SetFundingAccounts sets the FundingAccounts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFundingRecipient) SetFundingAccounts(fundingAccounts []*papisdkgo.FundingAccount) {
	c.FundingAccounts = fundingAccounts
	c.require(createFundingRecipientFieldFundingAccounts)
}

func (c *CreateFundingRecipient) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateFundingRecipient
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateFundingRecipient(body)
	return nil
}

func (c *CreateFundingRecipient) MarshalJSON() ([]byte, error) {
	type embed CreateFundingRecipient
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createAccountFundingRecipientsRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	createAccountFundingRecipientsRequestFieldRecipientId    = big.NewInt(1 << 1)
)

type CreateAccountFundingRecipientsRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int                       `json:"-" url:"-"`
	Body        *papisdkgo.FundingAccount `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateAccountFundingRecipientsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountFundingRecipientsRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createAccountFundingRecipientsRequestFieldIdempotencyKey)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountFundingRecipientsRequest) SetRecipientId(recipientId int) {
	c.RecipientId = recipientId
	c.require(createAccountFundingRecipientsRequestFieldRecipientId)
}

func (c *CreateAccountFundingRecipientsRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.FundingAccount)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateAccountFundingRecipientsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	createOwnerFundingRecipientsRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	createOwnerFundingRecipientsRequestFieldRecipientId    = big.NewInt(1 << 1)
)

type CreateOwnerFundingRecipientsRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int              `json:"-" url:"-"`
	Body        *papisdkgo.Owner `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateOwnerFundingRecipientsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateOwnerFundingRecipientsRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createOwnerFundingRecipientsRequestFieldIdempotencyKey)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateOwnerFundingRecipientsRequest) SetRecipientId(recipientId int) {
	c.RecipientId = recipientId
	c.require(createOwnerFundingRecipientsRequestFieldRecipientId)
}

func (c *CreateOwnerFundingRecipientsRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.Owner)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateOwnerFundingRecipientsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	deleteFundingRecipientsRequestFieldRecipientId = big.NewInt(1 << 0)
)

type DeleteFundingRecipientsRequest struct {
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteFundingRecipientsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFundingRecipientsRequest) SetRecipientId(recipientId int) {
	d.RecipientId = recipientId
	d.require(deleteFundingRecipientsRequestFieldRecipientId)
}

var (
	listFundingRecipientsRequestFieldBefore = big.NewInt(1 << 0)
	listFundingRecipientsRequestFieldAfter  = big.NewInt(1 << 1)
	listFundingRecipientsRequestFieldLimit  = big.NewInt(1 << 2)
)

type ListFundingRecipientsRequest struct {
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFundingRecipientsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingRecipientsRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listFundingRecipientsRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingRecipientsRequest) SetAfter(after *string) {
	l.After = after
	l.require(listFundingRecipientsRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingRecipientsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFundingRecipientsRequestFieldLimit)
}

var (
	listFundingRecipientFundingAccountsRequestFieldRecipientId = big.NewInt(1 << 0)
)

type ListFundingRecipientFundingAccountsRequest struct {
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFundingRecipientFundingAccountsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingRecipientFundingAccountsRequest) SetRecipientId(recipientId int) {
	l.RecipientId = recipientId
	l.require(listFundingRecipientFundingAccountsRequestFieldRecipientId)
}

var (
	listFundingRecipientOwnersRequestFieldRecipientId = big.NewInt(1 << 0)
)

type ListFundingRecipientOwnersRequest struct {
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFundingRecipientOwnersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFundingRecipientOwnersRequest) SetRecipientId(recipientId int) {
	l.RecipientId = recipientId
	l.require(listFundingRecipientOwnersRequestFieldRecipientId)
}

var (
	retrieveFundingRecipientsRequestFieldRecipientId = big.NewInt(1 << 0)
)

type RetrieveFundingRecipientsRequest struct {
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveFundingRecipientsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveFundingRecipientsRequest) SetRecipientId(recipientId int) {
	r.RecipientId = recipientId
	r.require(retrieveFundingRecipientsRequestFieldRecipientId)
}

// Type or legal structure of the funding recipient.
type CreateFundingRecipientRecipientType string

const (
	CreateFundingRecipientRecipientTypePrivateCorporation CreateFundingRecipientRecipientType = "privateCorporation"
	CreateFundingRecipientRecipientTypePublicCorporation  CreateFundingRecipientRecipientType = "publicCorporation"
	CreateFundingRecipientRecipientTypeNonProfit          CreateFundingRecipientRecipientType = "nonProfit"
	CreateFundingRecipientRecipientTypeGovernment         CreateFundingRecipientRecipientType = "government"
	CreateFundingRecipientRecipientTypePrivateLlc         CreateFundingRecipientRecipientType = "privateLlc"
	CreateFundingRecipientRecipientTypePublicLlc          CreateFundingRecipientRecipientType = "publicLlc"
	CreateFundingRecipientRecipientTypePrivatePartnership CreateFundingRecipientRecipientType = "privatePartnership"
	CreateFundingRecipientRecipientTypePublicPartnership  CreateFundingRecipientRecipientType = "publicPartnership"
	CreateFundingRecipientRecipientTypeSoleProprietor     CreateFundingRecipientRecipientType = "soleProprietor"
)

func NewCreateFundingRecipientRecipientTypeFromString(s string) (CreateFundingRecipientRecipientType, error) {
	switch s {
	case "privateCorporation":
		return CreateFundingRecipientRecipientTypePrivateCorporation, nil
	case "publicCorporation":
		return CreateFundingRecipientRecipientTypePublicCorporation, nil
	case "nonProfit":
		return CreateFundingRecipientRecipientTypeNonProfit, nil
	case "government":
		return CreateFundingRecipientRecipientTypeGovernment, nil
	case "privateLlc":
		return CreateFundingRecipientRecipientTypePrivateLlc, nil
	case "publicLlc":
		return CreateFundingRecipientRecipientTypePublicLlc, nil
	case "privatePartnership":
		return CreateFundingRecipientRecipientTypePrivatePartnership, nil
	case "publicPartnership":
		return CreateFundingRecipientRecipientTypePublicPartnership, nil
	case "soleProprietor":
		return CreateFundingRecipientRecipientTypeSoleProprietor, nil
	}
	var t CreateFundingRecipientRecipientType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateFundingRecipientRecipientType) Ptr() *CreateFundingRecipientRecipientType {
	return &c
}

var (
	updateFundingRecipientsRequestFieldRecipientId = big.NewInt(1 << 0)
)

type UpdateFundingRecipientsRequest struct {
	// Unique identifier that we assigned to the funding recipient.
	RecipientId int                         `json:"-" url:"-"`
	Body        *papisdkgo.FundingRecipient `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateFundingRecipientsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetRecipientId sets the RecipientId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateFundingRecipientsRequest) SetRecipientId(recipientId int) {
	u.RecipientId = recipientId
	u.require(updateFundingRecipientsRequestFieldRecipientId)
}

func (u *UpdateFundingRecipientsRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.FundingRecipient)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdateFundingRecipientsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}
