// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	securetokens "github.com/payroc/payroc-sdk-go/tokenization/securetokens"
	singleusetokens "github.com/payroc/payroc-sdk-go/tokenization/singleusetokens"
)

type Client struct {
	SecureTokens    *securetokens.Client
	SingleUseTokens *singleusetokens.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		SecureTokens:    securetokens.NewClient(options),
		SingleUseTokens: singleusetokens.NewClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
