// Code generated by Fern. DO NOT EDIT.

package client

import (
	payments "github.com/payroc/payroc-sdk-go/banktransferpayments/payments"
	refunds "github.com/payroc/payroc-sdk-go/banktransferpayments/refunds"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
)

type Client struct {
	Payments *payments.Client
	Refunds  *refunds.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Payments: payments.NewClient(options),
		Refunds:  refunds.NewClient(options),
		options:  options,
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
