// Code generated by Fern. DO NOT EDIT.

package fundingactivity

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	core "github.com/payroc/payroc-sdk-go/core"
	funding "github.com/payroc/payroc-sdk-go/funding"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Use this method to return a [paginated](https://docs.payroc.com/api/pagination) list of funding balances available for each merchant linked to your account.
//
// Use query parameters to filter the list of results we return, for example, to search for the funding balance for a specific merchant.
//
// Our gateway returns the following information about each merchant in the list:
// - Total funds for the merchant.
// - Available funds that you can use for funding instructions.
// - Pending funds that we have not yet sent to funding accounts.
func (c *Client) RetrieveBalance(
	ctx context.Context,
	request *funding.RetrieveBalanceFundingActivityRequest,
	opts ...option.RequestOption,
) (*funding.RetrieveBalanceFundingActivityResponse, error) {
	response, err := c.WithRawResponse.RetrieveBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to return a [paginated](https://docs.payroc.com/api/pagination) list of activity associated with your merchants' funding balances within a specific date range.
//
// Use query parameters to filter the list of results we return, for example, to view the activity for a specific merchant's funding balance.
//
// Our gateway returns the following information about each activity in the list:
// - Name of the merchant who owns the funding balance.
// -	Amount of funds added or removed from the funding balance.
// -	Funding account that received funds from the funding balance.
func (c *Client) List(
	ctx context.Context,
	request *funding.ListFundingActivityRequest,
	opts ...option.RequestOption,
) (*core.PayrocPager[*funding.ListFundingActivityResponse, []*payroc.ActivityRecord, *payroc.Link], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		c.baseURL,
		internal.ResolveEnvironmentBaseURL(
			c.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/funding-activity"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	response, callErr := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if callErr != nil {
		return nil, callErr
	}
	var responseBody *funding.ListFundingActivityResponse = response.Body
	fetcher := func(
		ctx context.Context,
		href string,
	) (*funding.ListFundingActivityResponse, error) {
		options := core.NewRequestOptions(opts...)
		headers := internal.MergeHeaders(
			c.options.ToHeader(),
			options.ToHeader(),
		)
		var pageResponse *funding.ListFundingActivityResponse
		_, err := c.caller.Call(ctx, &internal.CallParams{
			URL:             href,
			Method:          "GET",
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &pageResponse,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		})
		if err != nil {
			return nil, err
		}
		return pageResponse, nil
	}
	pager := core.NewPayrocPager(responseBody, fetcher)
	return pager, nil
}
