// Code generated by Fern. DO NOT EDIT.

package repeatpayments

import (
	json "encoding/json"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	big "math/big"
)

var (
	createPaymentPlansRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	createPaymentPlansRequestFieldProcessingTerminalId = big.NewInt(1 << 1)
)

type CreatePaymentPlansRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string                 `json:"-" url:"-"`
	Body                 *papisdkgo.PaymentPlan `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePaymentPlansRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePaymentPlansRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createPaymentPlansRequestFieldIdempotencyKey)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePaymentPlansRequest) SetProcessingTerminalId(processingTerminalId string) {
	c.ProcessingTerminalId = processingTerminalId
	c.require(createPaymentPlansRequestFieldProcessingTerminalId)
}

func (c *CreatePaymentPlansRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.PaymentPlan)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreatePaymentPlansRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	deletePaymentPlansRequestFieldProcessingTerminalId = big.NewInt(1 << 0)
	deletePaymentPlansRequestFieldPaymentPlanId        = big.NewInt(1 << 1)
)

type DeletePaymentPlansRequest struct {
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the payment plan.
	PaymentPlanId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePaymentPlansRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePaymentPlansRequest) SetProcessingTerminalId(processingTerminalId string) {
	d.ProcessingTerminalId = processingTerminalId
	d.require(deletePaymentPlansRequestFieldProcessingTerminalId)
}

// SetPaymentPlanId sets the PaymentPlanId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePaymentPlansRequest) SetPaymentPlanId(paymentPlanId string) {
	d.PaymentPlanId = paymentPlanId
	d.require(deletePaymentPlansRequestFieldPaymentPlanId)
}

var (
	listPaymentPlansRequestFieldProcessingTerminalId = big.NewInt(1 << 0)
	listPaymentPlansRequestFieldBefore               = big.NewInt(1 << 1)
	listPaymentPlansRequestFieldAfter                = big.NewInt(1 << 2)
	listPaymentPlansRequestFieldLimit                = big.NewInt(1 << 3)
)

type ListPaymentPlansRequest struct {
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPaymentPlansRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPlansRequest) SetProcessingTerminalId(processingTerminalId string) {
	l.ProcessingTerminalId = processingTerminalId
	l.require(listPaymentPlansRequestFieldProcessingTerminalId)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPlansRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listPaymentPlansRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPlansRequest) SetAfter(after *string) {
	l.After = after
	l.require(listPaymentPlansRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPlansRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listPaymentPlansRequestFieldLimit)
}

var (
	partiallyUpdatePaymentPlansRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	partiallyUpdatePaymentPlansRequestFieldProcessingTerminalId = big.NewInt(1 << 1)
	partiallyUpdatePaymentPlansRequestFieldPaymentPlanId        = big.NewInt(1 << 2)
)

type PartiallyUpdatePaymentPlansRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the payment plan.
	PaymentPlanId string                 `json:"-" url:"-"`
	Body          papisdkgo.PatchRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PartiallyUpdatePaymentPlansRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PartiallyUpdatePaymentPlansRequest) SetIdempotencyKey(idempotencyKey string) {
	p.IdempotencyKey = idempotencyKey
	p.require(partiallyUpdatePaymentPlansRequestFieldIdempotencyKey)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PartiallyUpdatePaymentPlansRequest) SetProcessingTerminalId(processingTerminalId string) {
	p.ProcessingTerminalId = processingTerminalId
	p.require(partiallyUpdatePaymentPlansRequestFieldProcessingTerminalId)
}

// SetPaymentPlanId sets the PaymentPlanId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PartiallyUpdatePaymentPlansRequest) SetPaymentPlanId(paymentPlanId string) {
	p.PaymentPlanId = paymentPlanId
	p.require(partiallyUpdatePaymentPlansRequestFieldPaymentPlanId)
}

func (p *PartiallyUpdatePaymentPlansRequest) UnmarshalJSON(data []byte) error {
	var body papisdkgo.PatchRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PartiallyUpdatePaymentPlansRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	retrievePaymentPlansRequestFieldProcessingTerminalId = big.NewInt(1 << 0)
	retrievePaymentPlansRequestFieldPaymentPlanId        = big.NewInt(1 << 1)
)

type RetrievePaymentPlansRequest struct {
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the payment plan.
	PaymentPlanId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrievePaymentPlansRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrievePaymentPlansRequest) SetProcessingTerminalId(processingTerminalId string) {
	r.ProcessingTerminalId = processingTerminalId
	r.require(retrievePaymentPlansRequestFieldProcessingTerminalId)
}

// SetPaymentPlanId sets the PaymentPlanId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrievePaymentPlansRequest) SetPaymentPlanId(paymentPlanId string) {
	r.PaymentPlanId = paymentPlanId
	r.require(retrievePaymentPlansRequestFieldPaymentPlanId)
}
