// Code generated by Fern. DO NOT EDIT.

package reporting_settlement_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payroc "github.com/payroc/payroc-sdk-go"
	client "github.com/payroc/payroc-sdk-go/client"
	option "github.com/payroc/payroc-sdk-go/option"
	reporting "github.com/payroc/payroc-sdk-go/reporting"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestReportingSettlementListBatchesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListReportingSettlementBatchesRequest{
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
		Date: payroc.MustParseDate(
			"2027-07-02",
		),
		MerchantId: payroc.String(
			"4525644354",
		),
	}
	_, invocationErr := client.Reporting.Settlement.ListBatches(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListBatchesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListBatchesWithWireMock", "GET", "/batches", map[string]string{"before": "2571", "after": "8516", "limit": "1", "date": "2027-07-02", "merchantId": "4525644354"}, 1)
}

func TestReportingSettlementRetrieveBatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.RetrieveBatchSettlementRequest{
		BatchId: 1,
	}
	_, invocationErr := client.Reporting.Settlement.RetrieveBatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementRetrieveBatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementRetrieveBatchWithWireMock", "GET", "/batches/1", nil, 1)
}

func TestReportingSettlementListTransactionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListReportingSettlementTransactionsRequest{
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
		Date: payroc.Time(
			payroc.MustParseDate(
				"2024-07-02",
			),
		),
		BatchId: payroc.Int(
			1,
		),
		MerchantId: payroc.String(
			"4525644354",
		),
		TransactionType: reporting.ListTransactionsSettlementRequestTransactionTypeCapture.Ptr(),
	}
	_, invocationErr := client.Reporting.Settlement.ListTransactions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListTransactionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListTransactionsWithWireMock", "GET", "/transactions", map[string]string{"before": "2571", "after": "8516", "limit": "1", "date": "2024-07-02", "batchId": "1", "merchantId": "4525644354", "transactionType": "Capture"}, 1)
}

func TestReportingSettlementRetrieveTransactionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.RetrieveTransactionSettlementRequest{
		TransactionId: 1,
	}
	_, invocationErr := client.Reporting.Settlement.RetrieveTransaction(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementRetrieveTransactionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementRetrieveTransactionWithWireMock", "GET", "/transactions/1", nil, 1)
}

func TestReportingSettlementListAuthorizationsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListReportingSettlementAuthorizationsRequest{
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
		Date: payroc.Time(
			payroc.MustParseDate(
				"2024-07-02",
			),
		),
		BatchId: payroc.Int(
			1,
		),
		MerchantId: payroc.String(
			"4525644354",
		),
	}
	_, invocationErr := client.Reporting.Settlement.ListAuthorizations(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListAuthorizationsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListAuthorizationsWithWireMock", "GET", "/authorizations", map[string]string{"before": "2571", "after": "8516", "limit": "1", "date": "2024-07-02", "batchId": "1", "merchantId": "4525644354"}, 1)
}

func TestReportingSettlementRetrieveAuthorizationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.RetrieveAuthorizationSettlementRequest{
		AuthorizationId: 1,
	}
	_, invocationErr := client.Reporting.Settlement.RetrieveAuthorization(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementRetrieveAuthorizationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementRetrieveAuthorizationWithWireMock", "GET", "/authorizations/1", nil, 1)
}

func TestReportingSettlementListDisputesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListReportingSettlementDisputesRequest{
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
		Date: payroc.MustParseDate(
			"2024-07-02",
		),
		MerchantId: payroc.String(
			"4525644354",
		),
	}
	_, invocationErr := client.Reporting.Settlement.ListDisputes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListDisputesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListDisputesWithWireMock", "GET", "/disputes", map[string]string{"before": "2571", "after": "8516", "limit": "1", "date": "2024-07-02", "merchantId": "4525644354"}, 1)
}

func TestReportingSettlementListDisputesStatusesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListDisputesStatusesSettlementRequest{
		DisputeId: 1,
	}
	_, invocationErr := client.Reporting.Settlement.ListDisputesStatuses(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListDisputesStatusesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListDisputesStatusesWithWireMock", "GET", "/disputes/1/statuses", nil, 1)
}

func TestReportingSettlementListAchDepositsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListReportingSettlementAchDepositsRequest{
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
		Date: payroc.MustParseDate(
			"2024-07-02",
		),
		MerchantId: payroc.String(
			"4525644354",
		),
	}
	_, invocationErr := client.Reporting.Settlement.ListAchDeposits(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListAchDepositsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListAchDepositsWithWireMock", "GET", "/ach-deposits", map[string]string{"before": "2571", "after": "8516", "limit": "1", "date": "2024-07-02", "merchantId": "4525644354"}, 1)
}

func TestReportingSettlementRetrieveAchDepositWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.RetrieveAchDepositSettlementRequest{
		AchDepositId: 1,
	}
	_, invocationErr := client.Reporting.Settlement.RetrieveAchDeposit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementRetrieveAchDepositWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementRetrieveAchDepositWithWireMock", "GET", "/ach-deposits/1", nil, 1)
}

func TestReportingSettlementListAchDepositFeesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &reporting.ListReportingSettlementAchDepositFeesRequest{
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
		Date: payroc.Time(
			payroc.MustParseDate(
				"2024-07-02",
			),
		),
		AchDepositId: payroc.Int(
			1,
		),
		MerchantId: payroc.String(
			"4525644354",
		),
	}
	_, invocationErr := client.Reporting.Settlement.ListAchDepositFees(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReportingSettlementListAchDepositFeesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReportingSettlementListAchDepositFeesWithWireMock", "GET", "/ach-deposit-fees", map[string]string{"before": "2571", "after": "8516", "limit": "1", "date": "2024-07-02", "achDepositId": "1", "merchantId": "4525644354"}, 1)
}
