// Code generated by Fern. DO NOT EDIT.

package payroc_cloud_refund_instructions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payroc "github.com/payroc/payroc-sdk-go"
	client "github.com/payroc/payroc-sdk-go/client"
	option "github.com/payroc/payroc-sdk-go/option"
	payroccloud "github.com/payroc/payroc-sdk-go/payroccloud"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPayrocCloudRefundInstructionsSubmitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payroccloud.RefundInstructionRequest{
		SerialNumber:   "1850010868",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Operator: payroc.String(
			"Jane",
		),
		ProcessingTerminalId: "1234001",
		Order: &payroc.RefundInstructionOrder{
			OrderId: "OrderRef6543",
			Description: payroc.String(
				"Refund for order OrderRef6543",
			),
			Amount:   4999,
			Currency: payroc.CurrencyUsd,
		},
		CustomizationOptions: &payroc.CustomizationOptions{
			EntryMethod: payroc.CustomizationOptionsEntryMethodManualEntry.Ptr(),
		},
	}
	_, invocationErr := client.PayrocCloud.RefundInstructions.Submit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPayrocCloudRefundInstructionsSubmitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPayrocCloudRefundInstructionsSubmitWithWireMock", "POST", "/devices/1850010868/refund-instructions", nil, 1)
}

func TestPayrocCloudRefundInstructionsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payroccloud.RetrieveRefundInstructionsRequest{
		RefundInstructionId: "a37439165d134678a9100ebba3b29597",
	}
	_, invocationErr := client.PayrocCloud.RefundInstructions.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPayrocCloudRefundInstructionsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPayrocCloudRefundInstructionsRetrieveWithWireMock", "GET", "/refund-instructions/a37439165d134678a9100ebba3b29597", nil, 1)
}

func TestPayrocCloudRefundInstructionsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payroccloud.DeleteRefundInstructionsRequest{
		RefundInstructionId: "a37439165d134678a9100ebba3b29597",
	}
	invocationErr := client.PayrocCloud.RefundInstructions.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPayrocCloudRefundInstructionsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPayrocCloudRefundInstructionsDeleteWithWireMock", "DELETE", "/refund-instructions/a37439165d134678a9100ebba3b29597", nil, 1)
}
