// Code generated by Fern. DO NOT EDIT.

package cards

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	paymentfeatures "github.com/payroc/payroc-sdk-go/paymentfeatures"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) VerifyCard(
	ctx context.Context,
	request *paymentfeatures.CardVerificationRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.CardVerificationResult], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/cards/verify"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response *payroc.CardVerificationResult
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.CardVerificationResult]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ViewEbtBalance(
	ctx context.Context,
	request *paymentfeatures.BalanceInquiry,
	opts ...option.RequestOption,
) (*core.Response[*payroc.Balance], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/cards/balance"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *payroc.Balance
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.Balance]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) LookupBin(
	ctx context.Context,
	request *paymentfeatures.BinLookup,
	opts ...option.RequestOption,
) (*core.Response[*payroc.CardInfo], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/cards/bin-lookup"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *payroc.CardInfo
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.CardInfo]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RetrieveFxRates(
	ctx context.Context,
	request *paymentfeatures.FxRateInquiry,
	opts ...option.RequestOption,
) (*core.Response[*payroc.FxRate], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/fx-rates"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *payroc.FxRate
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.FxRate]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
