// Code generated by Fern. DO NOT EDIT.

package tokenization

import (
	json "encoding/json"
	fmt "fmt"
	papisdkgo "github.com/payroc/payroc-sdk-go"
	internal "github.com/payroc/payroc-sdk-go/internal"
	big "math/big"
)

var (
	tokenizationRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	tokenizationRequestFieldProcessingTerminalId = big.NewInt(1 << 1)
	tokenizationRequestFieldSecureTokenId        = big.NewInt(1 << 2)
	tokenizationRequestFieldOperator             = big.NewInt(1 << 3)
	tokenizationRequestFieldMitAgreement         = big.NewInt(1 << 4)
	tokenizationRequestFieldCustomer             = big.NewInt(1 << 5)
	tokenizationRequestFieldIpAddress            = big.NewInt(1 << 6)
	tokenizationRequestFieldSource               = big.NewInt(1 << 7)
	tokenizationRequestFieldThreeDSecure         = big.NewInt(1 << 8)
	tokenizationRequestFieldCustomFields         = big.NewInt(1 << 9)
)

type TokenizationRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant created for the secure token that represents the customer's payment details.
	// If the merchant doesn't create a secureTokenId, the gateway generates one and returns it in the response.
	SecureTokenId *string `json:"secureTokenId,omitempty" url:"-"`
	// Operator who saved the customer's payment details.
	Operator *string `json:"operator,omitempty" url:"-"`
	// Indicates how the merchant can use the customer's card details, as agreed by the customer:
	//
	// - `unscheduled` - Transactions for a fixed or variable amount that are run at a certain pre-defined event.
	// - `recurring` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Recurring transactions don't have a fixed duration and run until the customer cancels the agreement.
	// - `installment` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Installment transactions have a fixed duration.
	MitAgreement *TokenizationRequestMitAgreement `json:"mitAgreement,omitempty" url:"-"`
	Customer     *papisdkgo.Customer              `json:"customer,omitempty" url:"-"`
	IpAddress    *papisdkgo.IpAddress             `json:"ipAddress,omitempty" url:"-"`
	// Polymorphic object that contains the payment method to tokenize.
	//
	// The value of the type parameter determines which variant you should use:
	// -	`ach` - Automated Clearing House (ACH) details
	// -	`pad` - Pre-authorized debit (PAD) details
	// -	`card` - Payment card details
	// -	`singleUseToken` - Single-use token details
	Source *TokenizationRequestSource `json:"source" url:"-"`
	// Polymorphic object that contains authentication information from 3-D Secure.
	//
	// The value of the type parameter determines which variant you should use:
	// -	`gatewayThreeDSecure` - Use our gateway to run a 3-D Secure check.
	// -	`thirdPartyThreeDSecure` - Use a third party to run a 3-D Secure check.
	ThreeDSecure *TokenizationRequestThreeDSecure `json:"threeDSecure,omitempty" url:"-"`
	// Array of customField objects.
	CustomFields []*papisdkgo.CustomField `json:"customFields,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TokenizationRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetIdempotencyKey(idempotencyKey string) {
	t.IdempotencyKey = idempotencyKey
	t.require(tokenizationRequestFieldIdempotencyKey)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetProcessingTerminalId(processingTerminalId string) {
	t.ProcessingTerminalId = processingTerminalId
	t.require(tokenizationRequestFieldProcessingTerminalId)
}

// SetSecureTokenId sets the SecureTokenId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetSecureTokenId(secureTokenId *string) {
	t.SecureTokenId = secureTokenId
	t.require(tokenizationRequestFieldSecureTokenId)
}

// SetOperator sets the Operator field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetOperator(operator *string) {
	t.Operator = operator
	t.require(tokenizationRequestFieldOperator)
}

// SetMitAgreement sets the MitAgreement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetMitAgreement(mitAgreement *TokenizationRequestMitAgreement) {
	t.MitAgreement = mitAgreement
	t.require(tokenizationRequestFieldMitAgreement)
}

// SetCustomer sets the Customer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetCustomer(customer *papisdkgo.Customer) {
	t.Customer = customer
	t.require(tokenizationRequestFieldCustomer)
}

// SetIpAddress sets the IpAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetIpAddress(ipAddress *papisdkgo.IpAddress) {
	t.IpAddress = ipAddress
	t.require(tokenizationRequestFieldIpAddress)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetSource(source *TokenizationRequestSource) {
	t.Source = source
	t.require(tokenizationRequestFieldSource)
}

// SetThreeDSecure sets the ThreeDSecure field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetThreeDSecure(threeDSecure *TokenizationRequestThreeDSecure) {
	t.ThreeDSecure = threeDSecure
	t.require(tokenizationRequestFieldThreeDSecure)
}

// SetCustomFields sets the CustomFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenizationRequest) SetCustomFields(customFields []*papisdkgo.CustomField) {
	t.CustomFields = customFields
	t.require(tokenizationRequestFieldCustomFields)
}

func (t *TokenizationRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenizationRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*t = TokenizationRequest(body)
	return nil
}

func (t *TokenizationRequest) MarshalJSON() ([]byte, error) {
	type embed TokenizationRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteSecureTokensRequestFieldProcessingTerminalId = big.NewInt(1 << 0)
	deleteSecureTokensRequestFieldSecureTokenId        = big.NewInt(1 << 1)
)

type DeleteSecureTokensRequest struct {
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the secure token.
	SecureTokenId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSecureTokensRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSecureTokensRequest) SetProcessingTerminalId(processingTerminalId string) {
	d.ProcessingTerminalId = processingTerminalId
	d.require(deleteSecureTokensRequestFieldProcessingTerminalId)
}

// SetSecureTokenId sets the SecureTokenId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSecureTokensRequest) SetSecureTokenId(secureTokenId string) {
	d.SecureTokenId = secureTokenId
	d.require(deleteSecureTokensRequestFieldSecureTokenId)
}

var (
	listSecureTokensRequestFieldProcessingTerminalId = big.NewInt(1 << 0)
	listSecureTokensRequestFieldSecureTokenId        = big.NewInt(1 << 1)
	listSecureTokensRequestFieldCustomerName         = big.NewInt(1 << 2)
	listSecureTokensRequestFieldPhone                = big.NewInt(1 << 3)
	listSecureTokensRequestFieldEmail                = big.NewInt(1 << 4)
	listSecureTokensRequestFieldToken                = big.NewInt(1 << 5)
	listSecureTokensRequestFieldFirst6               = big.NewInt(1 << 6)
	listSecureTokensRequestFieldLast4                = big.NewInt(1 << 7)
	listSecureTokensRequestFieldBefore               = big.NewInt(1 << 8)
	listSecureTokensRequestFieldAfter                = big.NewInt(1 << 9)
	listSecureTokensRequestFieldLimit                = big.NewInt(1 << 10)
)

type ListSecureTokensRequest struct {
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the secure token.
	SecureTokenId *string `json:"-" url:"secureTokenId,omitempty"`
	// Filter by the customer's name.
	CustomerName *string `json:"-" url:"customerName,omitempty"`
	// Filter by the customer's phone number.
	Phone *string `json:"-" url:"phone,omitempty"`
	// Filter by the customer's email address.
	Email *string `json:"-" url:"email,omitempty"`
	// Filter by the token that the merchant used in a transaction to represent the customer's payment details.
	Token *string `json:"-" url:"token,omitempty"`
	// Filter by the first six digits of the card number.
	First6 *string `json:"-" url:"first6,omitempty"`
	// Filter by the last four digits of the card or account number.
	Last4 *string `json:"-" url:"last4,omitempty"`
	// Return the previous page of results before the value that you specify.
	//
	// You can’t send the before parameter in the same request as the after parameter.
	Before *string `json:"-" url:"before,omitempty"`
	// Return the next page of results after the value that you specify.
	//
	// You can’t send the after parameter in the same request as the before parameter.
	After *string `json:"-" url:"after,omitempty"`
	// Limit the maximum number of results that we return for each page.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSecureTokensRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetProcessingTerminalId(processingTerminalId string) {
	l.ProcessingTerminalId = processingTerminalId
	l.require(listSecureTokensRequestFieldProcessingTerminalId)
}

// SetSecureTokenId sets the SecureTokenId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetSecureTokenId(secureTokenId *string) {
	l.SecureTokenId = secureTokenId
	l.require(listSecureTokensRequestFieldSecureTokenId)
}

// SetCustomerName sets the CustomerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetCustomerName(customerName *string) {
	l.CustomerName = customerName
	l.require(listSecureTokensRequestFieldCustomerName)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetPhone(phone *string) {
	l.Phone = phone
	l.require(listSecureTokensRequestFieldPhone)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetEmail(email *string) {
	l.Email = email
	l.require(listSecureTokensRequestFieldEmail)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetToken(token *string) {
	l.Token = token
	l.require(listSecureTokensRequestFieldToken)
}

// SetFirst6 sets the First6 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetFirst6(first6 *string) {
	l.First6 = first6
	l.require(listSecureTokensRequestFieldFirst6)
}

// SetLast4 sets the Last4 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetLast4(last4 *string) {
	l.Last4 = last4
	l.require(listSecureTokensRequestFieldLast4)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listSecureTokensRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetAfter(after *string) {
	l.After = after
	l.require(listSecureTokensRequestFieldAfter)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSecureTokensRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listSecureTokensRequestFieldLimit)
}

var (
	partiallyUpdateSecureTokensRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	partiallyUpdateSecureTokensRequestFieldProcessingTerminalId = big.NewInt(1 << 1)
	partiallyUpdateSecureTokensRequestFieldSecureTokenId        = big.NewInt(1 << 2)
)

type PartiallyUpdateSecureTokensRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the secure token.
	SecureTokenId string                 `json:"-" url:"-"`
	Body          papisdkgo.PatchRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PartiallyUpdateSecureTokensRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PartiallyUpdateSecureTokensRequest) SetIdempotencyKey(idempotencyKey string) {
	p.IdempotencyKey = idempotencyKey
	p.require(partiallyUpdateSecureTokensRequestFieldIdempotencyKey)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PartiallyUpdateSecureTokensRequest) SetProcessingTerminalId(processingTerminalId string) {
	p.ProcessingTerminalId = processingTerminalId
	p.require(partiallyUpdateSecureTokensRequestFieldProcessingTerminalId)
}

// SetSecureTokenId sets the SecureTokenId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PartiallyUpdateSecureTokensRequest) SetSecureTokenId(secureTokenId string) {
	p.SecureTokenId = secureTokenId
	p.require(partiallyUpdateSecureTokensRequestFieldSecureTokenId)
}

func (p *PartiallyUpdateSecureTokensRequest) UnmarshalJSON(data []byte) error {
	var body papisdkgo.PatchRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PartiallyUpdateSecureTokensRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	retrieveSecureTokensRequestFieldProcessingTerminalId = big.NewInt(1 << 0)
	retrieveSecureTokensRequestFieldSecureTokenId        = big.NewInt(1 << 1)
)

type RetrieveSecureTokensRequest struct {
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the secure token.
	SecureTokenId string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveSecureTokensRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSecureTokensRequest) SetProcessingTerminalId(processingTerminalId string) {
	r.ProcessingTerminalId = processingTerminalId
	r.require(retrieveSecureTokensRequestFieldProcessingTerminalId)
}

// SetSecureTokenId sets the SecureTokenId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSecureTokensRequest) SetSecureTokenId(secureTokenId string) {
	r.SecureTokenId = secureTokenId
	r.require(retrieveSecureTokensRequestFieldSecureTokenId)
}

// Indicates how the merchant can use the customer's card details, as agreed by the customer:
//
// - `unscheduled` - Transactions for a fixed or variable amount that are run at a certain pre-defined event.
// - `recurring` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Recurring transactions don't have a fixed duration and run until the customer cancels the agreement.
// - `installment` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Installment transactions have a fixed duration.
type TokenizationRequestMitAgreement string

const (
	TokenizationRequestMitAgreementUnscheduled TokenizationRequestMitAgreement = "unscheduled"
	TokenizationRequestMitAgreementRecurring   TokenizationRequestMitAgreement = "recurring"
	TokenizationRequestMitAgreementInstallment TokenizationRequestMitAgreement = "installment"
)

func NewTokenizationRequestMitAgreementFromString(s string) (TokenizationRequestMitAgreement, error) {
	switch s {
	case "unscheduled":
		return TokenizationRequestMitAgreementUnscheduled, nil
	case "recurring":
		return TokenizationRequestMitAgreementRecurring, nil
	case "installment":
		return TokenizationRequestMitAgreementInstallment, nil
	}
	var t TokenizationRequestMitAgreement
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenizationRequestMitAgreement) Ptr() *TokenizationRequestMitAgreement {
	return &t
}

// Polymorphic object that contains the payment method to tokenize.
//
// The value of the type parameter determines which variant you should use:
// -	`ach` - Automated Clearing House (ACH) details
// -	`pad` - Pre-authorized debit (PAD) details
// -	`card` - Payment card details
// -	`singleUseToken` - Single-use token details
type TokenizationRequestSource struct {
	Type           string
	Ach            *papisdkgo.AchPayload
	Pad            *papisdkgo.PadPayload
	Card           *papisdkgo.CardPayload
	SingleUseToken *papisdkgo.SingleUseTokenPayload
}

func (t *TokenizationRequestSource) GetType() string {
	if t == nil {
		return ""
	}
	return t.Type
}

func (t *TokenizationRequestSource) GetAch() *papisdkgo.AchPayload {
	if t == nil {
		return nil
	}
	return t.Ach
}

func (t *TokenizationRequestSource) GetPad() *papisdkgo.PadPayload {
	if t == nil {
		return nil
	}
	return t.Pad
}

func (t *TokenizationRequestSource) GetCard() *papisdkgo.CardPayload {
	if t == nil {
		return nil
	}
	return t.Card
}

func (t *TokenizationRequestSource) GetSingleUseToken() *papisdkgo.SingleUseTokenPayload {
	if t == nil {
		return nil
	}
	return t.SingleUseToken
}

func (t *TokenizationRequestSource) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	t.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", t)
	}
	switch unmarshaler.Type {
	case "ach":
		value := new(papisdkgo.AchPayload)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Ach = value
	case "pad":
		value := new(papisdkgo.PadPayload)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Pad = value
	case "card":
		value := new(papisdkgo.CardPayload)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Card = value
	case "singleUseToken":
		value := new(papisdkgo.SingleUseTokenPayload)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.SingleUseToken = value
	}
	return nil
}

func (t TokenizationRequestSource) MarshalJSON() ([]byte, error) {
	if err := t.validate(); err != nil {
		return nil, err
	}
	if t.Ach != nil {
		return internal.MarshalJSONWithExtraProperty(t.Ach, "type", "ach")
	}
	if t.Pad != nil {
		return internal.MarshalJSONWithExtraProperty(t.Pad, "type", "pad")
	}
	if t.Card != nil {
		return internal.MarshalJSONWithExtraProperty(t.Card, "type", "card")
	}
	if t.SingleUseToken != nil {
		return internal.MarshalJSONWithExtraProperty(t.SingleUseToken, "type", "singleUseToken")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", t)
}

type TokenizationRequestSourceVisitor interface {
	VisitAch(*papisdkgo.AchPayload) error
	VisitPad(*papisdkgo.PadPayload) error
	VisitCard(*papisdkgo.CardPayload) error
	VisitSingleUseToken(*papisdkgo.SingleUseTokenPayload) error
}

func (t *TokenizationRequestSource) Accept(visitor TokenizationRequestSourceVisitor) error {
	if t.Ach != nil {
		return visitor.VisitAch(t.Ach)
	}
	if t.Pad != nil {
		return visitor.VisitPad(t.Pad)
	}
	if t.Card != nil {
		return visitor.VisitCard(t.Card)
	}
	if t.SingleUseToken != nil {
		return visitor.VisitSingleUseToken(t.SingleUseToken)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", t)
}

func (t *TokenizationRequestSource) validate() error {
	if t == nil {
		return fmt.Errorf("type %T is nil", t)
	}
	var fields []string
	if t.Ach != nil {
		fields = append(fields, "ach")
	}
	if t.Pad != nil {
		fields = append(fields, "pad")
	}
	if t.Card != nil {
		fields = append(fields, "card")
	}
	if t.SingleUseToken != nil {
		fields = append(fields, "singleUseToken")
	}
	if len(fields) == 0 {
		if t.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", t, t.Type)
		}
		return fmt.Errorf("type %T is empty", t)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", t, fields)
	}
	if t.Type != "" {
		field := fields[0]
		if t.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				t,
				t.Type,
				t,
			)
		}
	}
	return nil
}

// Polymorphic object that contains authentication information from 3-D Secure.
//
// The value of the type parameter determines which variant you should use:
// -	`gatewayThreeDSecure` - Use our gateway to run a 3-D Secure check.
// -	`thirdPartyThreeDSecure` - Use a third party to run a 3-D Secure check.
type TokenizationRequestThreeDSecure struct {
	Type                   string
	GatewayThreeDSecure    *papisdkgo.GatewayThreeDSecure
	ThirdPartyThreeDSecure *papisdkgo.ThirdPartyThreeDSecure
}

func (t *TokenizationRequestThreeDSecure) GetType() string {
	if t == nil {
		return ""
	}
	return t.Type
}

func (t *TokenizationRequestThreeDSecure) GetGatewayThreeDSecure() *papisdkgo.GatewayThreeDSecure {
	if t == nil {
		return nil
	}
	return t.GatewayThreeDSecure
}

func (t *TokenizationRequestThreeDSecure) GetThirdPartyThreeDSecure() *papisdkgo.ThirdPartyThreeDSecure {
	if t == nil {
		return nil
	}
	return t.ThirdPartyThreeDSecure
}

func (t *TokenizationRequestThreeDSecure) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	t.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", t)
	}
	switch unmarshaler.Type {
	case "gatewayThreeDSecure":
		value := new(papisdkgo.GatewayThreeDSecure)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.GatewayThreeDSecure = value
	case "thirdPartyThreeDSecure":
		value := new(papisdkgo.ThirdPartyThreeDSecure)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.ThirdPartyThreeDSecure = value
	}
	return nil
}

func (t TokenizationRequestThreeDSecure) MarshalJSON() ([]byte, error) {
	if err := t.validate(); err != nil {
		return nil, err
	}
	if t.GatewayThreeDSecure != nil {
		return internal.MarshalJSONWithExtraProperty(t.GatewayThreeDSecure, "type", "gatewayThreeDSecure")
	}
	if t.ThirdPartyThreeDSecure != nil {
		return internal.MarshalJSONWithExtraProperty(t.ThirdPartyThreeDSecure, "type", "thirdPartyThreeDSecure")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", t)
}

type TokenizationRequestThreeDSecureVisitor interface {
	VisitGatewayThreeDSecure(*papisdkgo.GatewayThreeDSecure) error
	VisitThirdPartyThreeDSecure(*papisdkgo.ThirdPartyThreeDSecure) error
}

func (t *TokenizationRequestThreeDSecure) Accept(visitor TokenizationRequestThreeDSecureVisitor) error {
	if t.GatewayThreeDSecure != nil {
		return visitor.VisitGatewayThreeDSecure(t.GatewayThreeDSecure)
	}
	if t.ThirdPartyThreeDSecure != nil {
		return visitor.VisitThirdPartyThreeDSecure(t.ThirdPartyThreeDSecure)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", t)
}

func (t *TokenizationRequestThreeDSecure) validate() error {
	if t == nil {
		return fmt.Errorf("type %T is nil", t)
	}
	var fields []string
	if t.GatewayThreeDSecure != nil {
		fields = append(fields, "gatewayThreeDSecure")
	}
	if t.ThirdPartyThreeDSecure != nil {
		fields = append(fields, "thirdPartyThreeDSecure")
	}
	if len(fields) == 0 {
		if t.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", t, t.Type)
		}
		return fmt.Errorf("type %T is empty", t)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", t, fields)
	}
	if t.Type != "" {
		field := fields[0]
		if t.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				t,
				t.Type,
				t,
			)
		}
	}
	return nil
}

var (
	updateAccountSecureTokensRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	updateAccountSecureTokensRequestFieldProcessingTerminalId = big.NewInt(1 << 1)
	updateAccountSecureTokensRequestFieldSecureTokenId        = big.NewInt(1 << 2)
)

type UpdateAccountSecureTokensRequest struct {
	// Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
	IdempotencyKey string `json:"-" url:"-"`
	// Unique identifier that we assigned to the terminal.
	ProcessingTerminalId string `json:"-" url:"-"`
	// Unique identifier that the merchant assigned to the secure token.
	SecureTokenId string                   `json:"-" url:"-"`
	Body          *papisdkgo.AccountUpdate `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateAccountSecureTokensRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAccountSecureTokensRequest) SetIdempotencyKey(idempotencyKey string) {
	u.IdempotencyKey = idempotencyKey
	u.require(updateAccountSecureTokensRequestFieldIdempotencyKey)
}

// SetProcessingTerminalId sets the ProcessingTerminalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAccountSecureTokensRequest) SetProcessingTerminalId(processingTerminalId string) {
	u.ProcessingTerminalId = processingTerminalId
	u.require(updateAccountSecureTokensRequestFieldProcessingTerminalId)
}

// SetSecureTokenId sets the SecureTokenId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAccountSecureTokensRequest) SetSecureTokenId(secureTokenId string) {
	u.SecureTokenId = secureTokenId
	u.require(updateAccountSecureTokensRequestFieldSecureTokenId)
}

func (u *UpdateAccountSecureTokensRequest) UnmarshalJSON(data []byte) error {
	body := new(papisdkgo.AccountUpdate)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdateAccountSecureTokensRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}
