// Code generated by Fern. DO NOT EDIT.

package signatureinstructions

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	payroccloud "github.com/payroc/payroc-sdk-go/payroccloud"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Use this method to submit an instruction to capture a customer's signature on a payment device.
//
// Our gateway returns information about the signature instruction and a signatureInstructionId, which you need for the following methods:
// - [Retrieve signature instruction](https://docs.payroc.com/api/schema/payroc-cloud/signature-instructions/retrieve) - View the details of the signature instruction.
// - [Cancel signature instruction](https://docs.payroc.com/api/schema/payroc-cloud/signature-instructions/delete) - Cancel the signature instruction.
func (c *Client) Submit(
	ctx context.Context,
	request *payroccloud.SignatureInstructionRequest,
	opts ...option.RequestOption,
) (*payroc.SignatureInstruction, error) {
	response, err := c.WithRawResponse.Submit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to retrieve information about a signature instruction.
//
// To retrieve a signature instruction, you need its signatureInstructionId. Our gateway returned the signatureInstructionId in the response of the [Submit Signature Instruction](https://docs.payroc.com/api/schema/payroc-cloud/signature-instructions/submit) method.
//
// Our gateway returns the status of the instruction. If the payment device completed the instruction, the response also includes a link to retrieve the signature.
func (c *Client) Retrieve(
	ctx context.Context,
	request *payroccloud.RetrieveSignatureInstructionsRequest,
	opts ...option.RequestOption,
) (*payroc.SignatureInstruction, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to cancel a signature instruction.
//
// To cancel a signature instruction, you need its signatureInstructionId. Our gateway returned the signatureInstructionId in the response of the [Submit signature instruction](https://docs.payroc.com/api/schema/payroc-cloud/signature-instructions/submit) method.
func (c *Client) Delete(
	ctx context.Context,
	request *payroccloud.DeleteSignatureInstructionsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
