// Code generated by Fern. DO NOT EDIT.

package pricingintents

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	boarding "github.com/payroc/payroc-sdk-go/boarding"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	request *boarding.ListPricingIntentsRequest,
	opts ...option.RequestOption,
) (*core.Response[*payroc.PaginatedPricingIntent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/pricing-intents"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payroc.PaginatedPricingIntent
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payroc.PaginatedPricingIntent]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *boarding.CreatePricingIntentsRequest,
	opts ...option.RequestOption,
) (*core.Response[payroc.PricingIntent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/pricing-intents"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response payroc.PricingIntent
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[payroc.PricingIntent]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Retrieve(
	ctx context.Context,
	request *boarding.RetrievePricingIntentsRequest,
	opts ...option.RequestOption,
) (*core.Response[payroc.PricingIntent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/pricing-intents/%v",
		request.PricingIntentId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response payroc.PricingIntent
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[payroc.PricingIntent]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *boarding.UpdatePricingIntentsRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/pricing-intents/%v",
		request.PricingIntentId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *boarding.DeletePricingIntentsRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/pricing-intents/%v",
		request.PricingIntentId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) PartiallyUpdate(
	ctx context.Context,
	request *boarding.PartiallyUpdatePricingIntentsRequest,
	opts ...option.RequestOption,
) (*core.Response[payroc.PricingIntent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/pricing-intents/%v",
		request.PricingIntentId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Idempotency-Key", request.IdempotencyKey)
	headers.Add("Content-Type", "application/json")
	var response payroc.PricingIntent
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[payroc.PricingIntent]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
