// Code generated by Fern. DO NOT EDIT.

package payments

import (
	context "context"
	payroc "github.com/payroc/payroc-sdk-go"
	cardpayments "github.com/payroc/payroc-sdk-go/cardpayments"
	core "github.com/payroc/payroc-sdk-go/core"
	internal "github.com/payroc/payroc-sdk-go/internal"
	option "github.com/payroc/payroc-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Use this method to return a [paginated](https://docs.payroc.com/api/pagination) list of payments.
//
// **Note:** If you want to view the details of a specific payment and you have its paymentId, use our [Retrieve Payment](https://docs.payroc.com/api/schema/card-payments/payments/retrieve) method.
//
// Use query parameters to filter the list of results that we return, for example, to search for payments for a customer, a tip mode, or a date range.
//
// Our gateway returns the following information about each payment in the list:
//
// - Order details, including the transaction amount and when it was processed.
// - Payment card details, including the masked card number, expiry date, and payment method.
// - Cardholder details, including their contact information and shipping address.
// - Payment details, including the payment type, status, and response.
//
// For each transaction, we also return the paymentId and an optional secureTokenId, which you can use to perform follow-on actions.
func (c *Client) List(
	ctx context.Context,
	request *cardpayments.ListPaymentsRequest,
	opts ...option.RequestOption,
) (*core.PayrocPager[*payroc.PaymentPaginatedListForRead, []*payroc.RetrievedPayment, *payroc.Link], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Api",
		),
		c.baseURL,
		internal.ResolveEnvironmentBaseURL(
			c.options.Environment,
			"Api",
		),
		"https://api.payroc.com/v1",
	)
	endpointURL := baseURL + "/payments"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	response, callErr := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if callErr != nil {
		return nil, callErr
	}
	var responseBody *payroc.PaymentPaginatedListForRead = response.Body
	fetcher := func(
		ctx context.Context,
		href string,
	) (*payroc.PaymentPaginatedListForRead, error) {
		options := core.NewRequestOptions(opts...)
		headers := internal.MergeHeaders(
			c.options.ToHeader(),
			options.ToHeader(),
		)
		var pageResponse *payroc.PaymentPaginatedListForRead
		_, err := c.caller.Call(ctx, &internal.CallParams{
			URL:             href,
			Method:          "GET",
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &pageResponse,
			ErrorDecoder:    internal.NewErrorDecoder(payroc.ErrorCodes),
		})
		if err != nil {
			return nil, err
		}
		return pageResponse, nil
	}
	pager := core.NewPayrocPager(responseBody, fetcher)
	return pager, nil
}

// Use this method to run a sale or a pre-authorization with a customer's payment card.
//
// In the response, our gateway returns information about the card payment and a paymentId, which you need for the following methods:
//
// -	[Retrieve payment](https://docs.payroc.com/api/schema/card-payments/payments/retrieve) - View the details of the card payment.
// -	[Adjust payment](https://docs.payroc.com/api/schema/card-payments/payments/adjust) - Update the details of the card payment.
// -	[Capture payment](https://docs.payroc.com/api/schema/card-payments/payments/capture)  - Capture the pre-authorization.
// -	[Reverse payment](https://docs.payroc.com/api/schema/card-payments/refunds/reverse)  - Cancel the card payment if it's in an open batch.
// -	[Refund payment](https://docs.payroc.com/api/schema/card-payments/refunds/create-referenced-refund)  - Run a referenced refund to return funds to the payment card.
//
// **Payment methods**
//
// - **Cards** - Credit, debit, and EBT
// - **Digital wallets** - [Apple Pay®](https://docs.payroc.com/guides/integrate/apple-pay) and [Google Pay®](https://docs.payroc.com/guides/integrate/google-pay)
// - **Tokens** - Secure tokens and single-use tokens
//
// **Features**
//
// Our Create Payment method also supports the following features:
//
// - [Repeat payments](https://docs.payroc.com/guides/integrate/repeat-payments/use-your-own-software) - Run multiple payments as part of a payment schedule that you manage with your own software.
// - **Offline sales** - Run a sale or a pre-authorization if the terminal loses its connection to our gateway.
// - [Tokenization](https://docs.payroc.com/guides/integrate/save-payment-details) - Save card details to use in future transactions.
// - [3-D Secure](https://docs.payroc.com/guides/integrate/3-d-secure) - Verify the identity of the cardholder.
// - [Custom fields](https://docs.payroc.com/guides/integrate/add-custom-fields) - Add your own data to a payment.
// - **Tips** - Add tips to the card payment.
// - **Taxes** - Add local taxes to the card payment.
// - **Surcharging** - Add a surcharge to the card payment.
// - **Dual pricing** - Offer different prices based on payment method, for example, if you use our RewardPay Choice pricing program.
func (c *Client) Create(
	ctx context.Context,
	request *cardpayments.PaymentRequest,
	opts ...option.RequestOption,
) (*payroc.Payment, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to retrieve information about a card payment.
//
// To retrieve a payment, you need its paymentId. Our gateway returned the paymentId in the response of the [Create Payment](https://docs.payroc.com/api/schema/card-payments/payments/create) method.
//
// **Note:** If you don't have the paymentId, use our [List Payments](https://docs.payroc.com/api/schema/card-payments/payments/list) method to search for the payment.
//
// Our gateway returns the following information about the payment:
//
// - Order details, including the transaction amount and when it was processed.
// - Payment card details, including the masked card number, expiry date, and payment method.
// - Cardholder details, including their contact information and shipping address.
// - Payment details, including the payment type, status, and response.
//
// If the merchant saved the customer's card details, our gateway returns a secureTokenID, which you can use to perform follow-on actions.
func (c *Client) Retrieve(
	ctx context.Context,
	request *cardpayments.RetrievePaymentsRequest,
	opts ...option.RequestOption,
) (*payroc.RetrievedPayment, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to adjust a payment in an open batch.
//
// To adjust a payment, you need its paymentId. Our gateway returned the paymentId in the response of the [Create Payment](https://docs.payroc.com/api/schema/card-payments/payments/create) method.
//
// **Note:** If you don't have the paymentId, use our [List Payments](https://docs.payroc.com/api/schema/card-payments/payments/list) method to search for the payment.
//
// You can adjust the following details of the payment:
// - Sale amount and tip amount
// - Payment status
// - Cardholder shipping address and contact information
// - Cardholder signature data
//
// Our gateway returns information about the adjusted payment, including information about the payment card and the cardholder.
func (c *Client) Adjust(
	ctx context.Context,
	request *cardpayments.PaymentAdjustment,
	opts ...option.RequestOption,
) (*payroc.Payment, error) {
	response, err := c.WithRawResponse.Adjust(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Use this method to capture a pre-authorization.
//
// To capture a pre-authorization, you need its paymentId. Our gateway returned the paymentId in the response of the [Create Payment](https://docs.payroc.com/api/schema/card-payments/payments/create) method.
//
// **Note:** If you don't have the paymentId, use our [List Payments](https://docs.payroc.com/api/schema/card-payments/payments/list) method to search for the payment.
//
// Depending on the amount you want to capture, complete the following:
// -	**Capture the full amount of the pre-authorization** - Don't send a value for the amount parameter in your request.
// -	**Capture less than the amount of the pre-authorization** - Send a value for the amount parameter in your request.
// -	**Capture more than the amount of the pre-authorization** - Adjust the pre-authorization before you capture it. For more information about adjusting a pre-authorization, go to [Adjust Payment](https://docs.payroc.com/api/schema/card-payments/payments/adjust).
//
// If your request is successful, our gateway takes the amount from the payment card.
//
// **Note:** For more information about pre-authorizations and captures, go to [Run a pre-authorization](https://docs.payroc.com/guides/integrate/run-a-pre-authorization).
func (c *Client) Capture(
	ctx context.Context,
	request *cardpayments.PaymentCapture,
	opts ...option.RequestOption,
) (*payroc.Payment, error) {
	response, err := c.WithRawResponse.Capture(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
