// Code generated by Fern. DO NOT EDIT.

package card_payments_refunds_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payroc "github.com/payroc/payroc-sdk-go"
	cardpayments "github.com/payroc/payroc-sdk-go/cardpayments"
	client "github.com/payroc/payroc-sdk-go/client"
	option "github.com/payroc/payroc-sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCardPaymentsRefundsReverseWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.PaymentReversal{
		PaymentId:      "M2MJOG6O2Y",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Amount: payroc.Int64(
			4999,
		),
	}
	_, invocationErr := client.CardPayments.Refunds.Reverse(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsReverseWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsReverseWithWireMock", "POST", "/payments/M2MJOG6O2Y/reverse", nil, 1)
}

func TestCardPaymentsRefundsCreateReferencedRefundWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.ReferencedRefund{
		PaymentId:      "M2MJOG6O2Y",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Amount:         4999,
		Description:    "Refund for order OrderRef6543",
	}
	_, invocationErr := client.CardPayments.Refunds.CreateReferencedRefund(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsCreateReferencedRefundWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsCreateReferencedRefundWithWireMock", "POST", "/payments/M2MJOG6O2Y/refund", nil, 1)
}

func TestCardPaymentsRefundsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.ListRefundsRequest{
		ProcessingTerminalId: payroc.String(
			"1234001",
		),
		OrderId: payroc.String(
			"OrderRef6543",
		),
		Operator: payroc.String(
			"Jane",
		),
		CardholderName: payroc.String(
			"Sarah%20Hazel%20Hopper",
		),
		First6: payroc.String(
			"453985",
		),
		Last4: payroc.String(
			"7062",
		),
		Tender: cardpayments.ListRefundsRequestTenderEbt.Ptr(),
		DateFrom: payroc.Time(
			payroc.MustParseDateTime(
				"2024-07-01T15:30:00Z",
			),
		),
		DateTo: payroc.Time(
			payroc.MustParseDateTime(
				"2024-07-03T15:30:00Z",
			),
		),
		SettlementState: cardpayments.ListRefundsRequestSettlementStateSettled.Ptr(),
		SettlementDate: payroc.Time(
			payroc.MustParseDate(
				"2024-07-02",
			),
		),
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
	}
	_, invocationErr := client.CardPayments.Refunds.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsListWithWireMock", "GET", "/refunds", map[string]string{"processingTerminalId": "1234001", "orderId": "OrderRef6543", "operator": "Jane", "cardholderName": "Sarah%20Hazel%20Hopper", "first6": "453985", "last4": "7062", "tender": "ebt", "dateFrom": "2024-07-01T15:30:00Z", "dateTo": "2024-07-03T15:30:00Z", "settlementState": "settled", "settlementDate": "2024-07-02", "before": "2571", "after": "8516", "limit": "1"}, 1)
}

func TestCardPaymentsRefundsCreateUnreferencedRefundWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.UnreferencedRefund{
		IdempotencyKey:       "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Channel:              cardpayments.UnreferencedRefundChannelPos,
		ProcessingTerminalId: "1234001",
		Order: &payroc.RefundOrder{
			OrderId: payroc.String(
				"OrderRef6543",
			),
			Description: payroc.String(
				"Refund for order OrderRef6543",
			),
			Amount: payroc.Int64(
				4999,
			),
			Currency: payroc.CurrencyUsd.Ptr(),
		},
		RefundMethod: &cardpayments.UnreferencedRefundRefundMethod{
			Card: &payroc.CardPayload{
				CardDetails: &payroc.CardPayloadCardDetails{
					Raw: &payroc.RawCardDetails{
						Device: &payroc.Device{
							Model:        payroc.DeviceModelBbposChp,
							SerialNumber: "1850010868",
						},
						RawData: "A1B2C3D4E5F67890ABCD1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF",
					},
				},
			},
		},
		CustomFields: []*payroc.CustomField{
			&payroc.CustomField{
				Name:  "yourCustomField",
				Value: "abc123",
			},
		},
	}
	_, invocationErr := client.CardPayments.Refunds.CreateUnreferencedRefund(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsCreateUnreferencedRefundWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsCreateUnreferencedRefundWithWireMock", "POST", "/refunds", nil, 1)
}

func TestCardPaymentsRefundsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.RetrieveRefundsRequest{
		RefundId: "CD3HN88U9F",
	}
	_, invocationErr := client.CardPayments.Refunds.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsRetrieveWithWireMock", "GET", "/refunds/CD3HN88U9F", nil, 1)
}

func TestCardPaymentsRefundsAdjustWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.RefundAdjustment{
		RefundId:       "CD3HN88U9F",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Operator: payroc.String(
			"Jane",
		),
		Adjustments: []*cardpayments.RefundAdjustmentAdjustmentsItem{
			&cardpayments.RefundAdjustmentAdjustmentsItem{
				Customer: &payroc.CustomerAdjustment{},
			},
		},
	}
	_, invocationErr := client.CardPayments.Refunds.Adjust(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsAdjustWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsAdjustWithWireMock", "POST", "/refunds/CD3HN88U9F/adjust", nil, 1)
}

func TestCardPaymentsRefundsReverseRefundWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.ReverseRefundRefundsRequest{
		RefundId:       "CD3HN88U9F",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
	}
	_, invocationErr := client.CardPayments.Refunds.ReverseRefund(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsRefundsReverseRefundWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsRefundsReverseRefundWithWireMock", "POST", "/refunds/CD3HN88U9F/reverse", nil, 1)
}
