// Code generated by Fern. DO NOT EDIT.

package card_payments_payments_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payroc "github.com/payroc/payroc-sdk-go"
	cardpayments "github.com/payroc/payroc-sdk-go/cardpayments"
	client "github.com/payroc/payroc-sdk-go/client"
	option "github.com/payroc/payroc-sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCardPaymentsPaymentsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.ListPaymentsRequest{
		ProcessingTerminalId: payroc.String(
			"1234001",
		),
		OrderId: payroc.String(
			"OrderRef6543",
		),
		Operator: payroc.String(
			"Jane",
		),
		CardholderName: payroc.String(
			"Sarah%20Hazel%20Hopper",
		),
		First6: payroc.String(
			"453985",
		),
		Last4: payroc.String(
			"7062",
		),
		Tender: cardpayments.ListPaymentsRequestTenderEbt.Ptr(),
		DateFrom: payroc.Time(
			payroc.MustParseDateTime(
				"2024-07-01T15:30:00Z",
			),
		),
		DateTo: payroc.Time(
			payroc.MustParseDateTime(
				"2024-07-03T15:30:00Z",
			),
		),
		SettlementState: cardpayments.ListPaymentsRequestSettlementStateSettled.Ptr(),
		SettlementDate: payroc.Time(
			payroc.MustParseDate(
				"2024-07-02",
			),
		),
		PaymentLinkId: payroc.String(
			"JZURRJBUPS",
		),
		Before: payroc.String(
			"2571",
		),
		After: payroc.String(
			"8516",
		),
		Limit: payroc.Int(
			1,
		),
	}
	_, invocationErr := client.CardPayments.Payments.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsPaymentsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsPaymentsListWithWireMock", "GET", "/payments", map[string]string{"processingTerminalId": "1234001", "orderId": "OrderRef6543", "operator": "Jane", "cardholderName": "Sarah%20Hazel%20Hopper", "first6": "453985", "last4": "7062", "tender": "ebt", "dateFrom": "2024-07-01T15:30:00Z", "dateTo": "2024-07-03T15:30:00Z", "settlementState": "settled", "settlementDate": "2024-07-02", "paymentLinkId": "JZURRJBUPS", "before": "2571", "after": "8516", "limit": "1"}, 1)
}

func TestCardPaymentsPaymentsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.PaymentRequest{
		IdempotencyKey:       "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Channel:              cardpayments.PaymentRequestChannelWeb,
		ProcessingTerminalId: "1234001",
		Operator: payroc.String(
			"Jane",
		),
		Order: &payroc.PaymentOrderRequest{
			OrderId: payroc.String(
				"OrderRef6543",
			),
			Description: payroc.String(
				"Large Pepperoni Pizza",
			),
			Amount: payroc.Int64(
				4999,
			),
			Currency: payroc.CurrencyUsd.Ptr(),
		},
		Customer: &payroc.Customer{
			FirstName: payroc.String(
				"Sarah",
			),
			LastName: payroc.String(
				"Hopper",
			),
			BillingAddress: &payroc.Address{
				Address1: "1 Example Ave.",
				Address2: payroc.String(
					"Example Address Line 2",
				),
				Address3: payroc.String(
					"Example Address Line 3",
				),
				City:       "Chicago",
				State:      "Illinois",
				Country:    "US",
				PostalCode: "60056",
			},
			ShippingAddress: &payroc.Shipping{
				RecipientName: payroc.String(
					"Sarah Hopper",
				),
				Address: &payroc.Address{
					Address1: "1 Example Ave.",
					Address2: payroc.String(
						"Example Address Line 2",
					),
					Address3: payroc.String(
						"Example Address Line 3",
					),
					City:       "Chicago",
					State:      "Illinois",
					Country:    "US",
					PostalCode: "60056",
				},
			},
		},
		PaymentMethod: &cardpayments.PaymentRequestPaymentMethod{
			Card: &payroc.CardPayload{
				CardDetails: &payroc.CardPayloadCardDetails{
					Raw: &payroc.RawCardDetails{
						Device: &payroc.Device{
							Model:        payroc.DeviceModelBbposChp,
							SerialNumber: "1850010868",
						},
						RawData: "A1B2C3D4E5F67890ABCD1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF",
					},
				},
			},
		},
		CustomFields: []*payroc.CustomField{
			&payroc.CustomField{
				Name:  "yourCustomField",
				Value: "abc123",
			},
		},
	}
	_, invocationErr := client.CardPayments.Payments.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsPaymentsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsPaymentsCreateWithWireMock", "POST", "/payments", nil, 1)
}

func TestCardPaymentsPaymentsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.RetrievePaymentsRequest{
		PaymentId: "M2MJOG6O2Y",
	}
	_, invocationErr := client.CardPayments.Payments.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsPaymentsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsPaymentsRetrieveWithWireMock", "GET", "/payments/M2MJOG6O2Y", nil, 1)
}

func TestCardPaymentsPaymentsAdjustWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.PaymentAdjustment{
		PaymentId:      "M2MJOG6O2Y",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
		Adjustments: []*cardpayments.PaymentAdjustmentAdjustmentsItem{
			&cardpayments.PaymentAdjustmentAdjustmentsItem{
				Customer: &payroc.CustomerAdjustment{},
			},
			&cardpayments.PaymentAdjustmentAdjustmentsItem{
				Order: &payroc.OrderAdjustment{
					Amount: 4999,
				},
			},
		},
	}
	_, invocationErr := client.CardPayments.Payments.Adjust(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsPaymentsAdjustWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsPaymentsAdjustWithWireMock", "POST", "/payments/M2MJOG6O2Y/adjust", nil, 1)
}

func TestCardPaymentsPaymentsCaptureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewPayrocClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &cardpayments.PaymentCapture{
		PaymentId:      "M2MJOG6O2Y",
		IdempotencyKey: "8e03978e-40d5-43e8-bc93-6894a57f9324",
		ProcessingTerminalId: payroc.String(
			"1234001",
		),
		Operator: payroc.String(
			"Jane",
		),
		Amount: payroc.Int64(
			4999,
		),
		Breakdown: &payroc.ItemizedBreakdownRequest{
			Subtotal: 4999,
			DutyAmount: payroc.Int64(
				499,
			),
			FreightAmount: payroc.Int64(
				500,
			),
			Items: []*payroc.LineItemRequest{
				&payroc.LineItemRequest{
					UnitPrice: 4000,
					Quantity:  1,
				},
			},
		},
	}
	_, invocationErr := client.CardPayments.Payments.Capture(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCardPaymentsPaymentsCaptureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCardPaymentsPaymentsCaptureWithWireMock", "POST", "/payments/M2MJOG6O2Y/capture", nil, 1)
}
